"""Verify relationship identities and inference attribution from offline evidence."""

# Future Library
from __future__ import annotations

# Standard Library
import hashlib
import json
import socket

from operator import itemgetter
from pathlib import Path
from typing import Any
from unittest.mock import Mock
from uuid import UUID

# Third Party Library
import pytest

# Package Library
from kgfeg.config import Settings
from kgfeg.kgs import lp_finalization
from kgfeg.kgs.lp_finalization import (
    LPFinalClaims,
    LPFinalizationCycleError,
    LPRelationships,
    build_lp_relationships,
)
from kgfeg.kgs.lp_generation import LPGenerationFailed
from kgfeg.kgs.schemas import Relationship
from kgfeg.kgs.utils import KGDirs
from tests.kgfeg.kgs import test_lp_finalization as _claims
from tests.kgfeg.kgs import test_lp_generation as _fixtures
from tests.kgfeg.kgs import test_lp_orchestration as _storage

_DOC_KEY = "synthetic-selection-document"
_TEMPLATE = (
    "Learning progression relationship generated by IDinsight using an LLM "
    "producer/checker workflow. Source framework attribution: "
    "{source_attribution_statement}. This inferred relationship was not stated "
    "or endorsed by the source publisher."
)
_PROFILES = (
    "ghana_english",
    "ghana_math",
    "madhi_math",
    "nigeria_math",
    "pratham_science",
    "rwanda_math",
)


def _assert_metadata(*, harness: _claims._Harness, rows: LPRelationships) -> None:
    """Compare ownership and every material reference with actual persisted inputs.

    Parameters
    ----------
    harness
        Authoritative synthetic inputs and offline adjudication directory.
    rows
        Minted rows under test, including embedded and separately keyed provenance.
    """
    root = harness.root
    final = LPFinalClaims.model_validate_json(
        (root / "lp_final_claims.json").read_bytes()
    )
    _claims._assert_provenance(artifact=final, root=root)
    candidates = _storage._rows(root / "lp_candidate_pairs.jsonl")
    requests = _storage._rows(root / "lp_generation_requests.jsonl")
    summary = json.loads((root / "lp_candidate_summary.json").read_bytes())
    receipt = json.loads((root / "lp_generation_checkpoint_manifest.json").read_bytes())
    material = receipt["material"]
    framework = harness.bundle.framework
    upstream = harness.bundle.model_dump(mode="json")
    for name, key in (
        ("items", "case_identifier_uuid"),
        ("learning_components", "identifier"),
        ("relationships_has_child", "identifier"),
        ("relationships_supports", "identifier"),
    ):
        upstream[name] = sorted(upstream[name], key=itemgetter(key))
    published = {
        (str(c.source_sfi_uuid), str(c.target_sfi_uuid), c.judgment.decision): c
        for c in final.claims
        if c.source_sfi_uuid is not None
    }
    edges = (*rows.relationships_builds_towards, *rows.relationships_relates_to)
    assert len(edges) == len(published) == len(rows.relationship_provenance)
    assert set(rows.relationship_provenance) == {str(edge.identifier) for edge in edges}
    assert rows.final_claims_content_hash == _claims._hash(
        final.model_dump(exclude={"content_hash"}, mode="json")
    )
    for edge in edges:
        claim = published[
            (edge.source_entity_value, edge.target_entity_value, edge.relationship_type)
        ]
        assert edge.source_entity == edge.target_entity == "StandardsFrameworkItem"
        assert (
            edge.source_entity_key == edge.target_entity_key == "case_identifier_uuid"
        )
        assert edge.source_entity_value != edge.target_entity_value
        endpoints = {str(item.case_identifier_uuid) for item in harness.bundle.items}
        assert {edge.source_entity_value, edge.target_entity_value} <= endpoints
        assert edge.author == "LLM generated"
        assert edge.provider == "IDinsight"
        assert edge.license == framework.license
        assert edge.attribution_statement == _TEMPLATE.replace(
            "{source_attribution_statement}", framework.attribution_statement
        )
        expected = {
            "approved_by": "IDinsight",
            "attribution_statement_template": _TEMPLATE,
            "candidate_artifact_byte_hashes": {
                name: hashlib.sha256((root / name).read_bytes()).hexdigest()
                for name in (
                    "lp_candidate_pairs.jsonl",
                    "lp_candidate_summary.json",
                    "lp_generation_requests.jsonl",
                )
            },
            "candidate_pairs_content_hash": _material_hash(candidates),
            "candidate_summary_content_hash": _material_hash(summary),
            "claim": claim.model_dump(mode="json"),
            "config_content_hash": _material_hash(
                harness.config.model_dump(by_alias=True, mode="json")
            ),
            "doc_key": _DOC_KEY,
            "effective_lp_config_content_hash": _claims._hash(
                harness.config.learning_progressions.model_dump(mode="json")
            ),
            "final_claims_content_hash": rows.final_claims_content_hash,
            "model_configuration": material["model_config"],
            "model_configuration_content_hash": _claims._hash(material["model_config"]),
            "model_settings": material["model_settings"],
            "model_settings_content_hash": _claims._hash(material["model_settings"]),
            "relationship_identity_key": (
                f"lc:curriculum:{_DOC_KEY}:relationship:{edge.relationship_type}:"
                f"{edge.source_entity_value}:{edge.target_entity_value}"
            ),
            "requests_content_hash": _material_hash(requests),
            "source_framework": {
                "attribution_statement": framework.attribution_statement,
                "author": framework.author,
                "case_identifier_uuid": str(framework.case_identifier_uuid),
                "license": framework.license,
                "provider": framework.provider,
                "title": framework.name,
            },
            "upstream_content_hash": _material_hash(upstream),
        }
        assert edge.metadata == expected
        assert (
            rows.relationship_provenance[str(edge.identifier)].model_dump(mode="json")
            == expected
        )
        assert claim.candidate.model_dump(mode="json") == next(
            c for c in candidates if c["pair_id"] == claim.judgment.pair_id
        )
        assert Relationship.model_validate_json(edge.model_dump_json()) == edge
    assert LPRelationships.model_validate_json(rows.model_dump_json()) == rows


@pytest.fixture(autouse=True)
def _block_network(monkeypatch: pytest.MonkeyPatch) -> None:
    """Forbid live model transport and pin a non-secret model identity.

    Parameters
    ----------
    monkeypatch
        Restoring network and model-setting substitutions.
    """
    guard = Mock(side_effect=AssertionError("Relationship tests must remain offline."))
    monkeypatch.setattr(name="connect", target=socket.socket, value=guard)
    monkeypatch.setattr(name="connect_ex", target=socket.socket, value=guard)
    monkeypatch.setattr(name="create_connection", target=socket, value=guard)
    monkeypatch.setattr(name="LLM_KG_MODEL", target=Settings, value="openai:gpt-5.2")


def _build(harness: _claims._Harness) -> LPRelationships:
    """Call the real read-only relationship boundary.

    Parameters
    ----------
    harness
        Completed input and evidence context.

    Returns
    -------
    LPRelationships
        Actual relationships with provenance.
    """
    return build_lp_relationships(
        as_lc_bundle=harness.bundle,
        doc_key=_DOC_KEY,
        kg_config=harness.config,
        kg_dirs=KGDirs(root=harness.root),
    )


def _material_hash(value: Any) -> str:
    """Hash canonical input JSON independently of production functions.

    Parameters
    ----------
    value
        Actual JSON material.

    Returns
    -------
    str
        SHA-256 of compact sorted Unicode JSON without a trailing newline.
    """
    return hashlib.sha256(
        json.dumps(
            allow_nan=False,
            ensure_ascii=False,
            obj=value,
            separators=(",", ":"),
            sort_keys=True,
        ).encode("utf-8")
    ).hexdigest()


def test_colliding_minted_relationship_ids_fail_closed(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """A collision between two published types cannot silently overwrite one row.

    Parameters
    ----------
    monkeypatch
        Offline model seam and controlled UUID collision injection.
    tmp_path
        Isolated evidence directory.
    """
    harness = _claims._Harness(count=3, root=tmp_path)
    harness.decisions = {
        (1, 2): ("buildsTowards", "first_to_second"),
        (2, 3): ("relatesTo", None),
    }
    _claims._install(harness=harness, monkeypatch=monkeypatch)
    harness._run()
    harness._finalize()
    before = _storage._snapshot(tmp_path)
    monkeypatch.setattr(
        name="uuid5", target=lp_finalization, value=Mock(return_value=UUID(int=500))
    )
    with pytest.raises(expected_exception=ValueError, match="identifiers collide"):
        _build(harness)
    assert _storage._snapshot(tmp_path) == before


@pytest.mark.parametrize(argnames="empty", argvalues=[None, "", " \n "])
@pytest.mark.parametrize(
    argnames="relation",
    argvalues=["buildsTowards", "hasChild", "relatesTo", "supports"],
)
def test_default_descriptions_disclose_semantics_and_preserve_existing_types(
    empty: str | None, relation: str
) -> None:
    """Fallback descriptions state inference semantics while retaining AS/LC wording.

    Parameters
    ----------
    empty
        Missing or blank description requiring the generic fallback.
    relation
        Existing or newly minted public relationship type.
    """
    payload = {
        "attribution_statement": "Synthetic attribution",
        "author": "Synthetic author",
        "description": empty,
        "identifier": str(UUID(int=900)),
        "license": "Synthetic license",
        "provider": "Synthetic provider",
        "relationship_type": relation,
        "source_entity": (
            "LearningComponent" if relation == "supports" else "StandardsFrameworkItem"
        ),
        "source_entity_key": (
            "identifier" if relation == "supports" else "case_identifier_uuid"
        ),
        "source_entity_value": str(UUID(int=1)),
        "target_entity": "StandardsFrameworkItem",
        "target_entity_key": "case_identifier_uuid",
        "target_entity_value": str(UUID(int=2)),
    }
    description = Relationship.model_validate(payload).description
    if relation == "buildsTowards":
        assert "proficiency" in description and "likelihood of success" in description
        assert "does not assert a mandatory prerequisite" in description
        assert "prerequisite progression" not in description
    elif relation == "relatesTo":
        assert "conceptual or skill coherence" in description
        assert "without asserting sequence or dependency" in description
        assert "technical, not semantic" in description
    else:
        assert (
            description
            == {
                "hasChild": "A hasChild relationship links a parent framework/item to a child standards item.",
                "supports": "A supports relationship links a learning component to a standards item it supports.",
            }[relation]
        )
    payload["description"] = "Existing explicit relationship description."
    assert Relationship.model_validate(payload).description == payload["description"]


@pytest.mark.parametrize(argnames="batch", argvalues=[1, 3])
def test_direct_checker_selected_edges_have_pinned_ids_and_exact_provenance(
    batch: int, monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """Retain every direct accepted edge and both model outcomes without closure.

    Parameters
    ----------
    batch
        Distinct request boundaries around the same six pairs.
    monkeypatch
        Offline producer/checker seam.
    tmp_path
        Isolated persisted artifacts.
    """
    harness = _claims._Harness(batch=batch, root=tmp_path)
    harness.decisions = {
        (1, 2): ("buildsTowards", "second_to_first"),
        (1, 3): ("relatesTo", None),
        (1, 4): ("needs_review", None),
        (2, 3): ("buildsTowards", "first_to_second"),
        (2, 4): ("no_relation", None),
        (3, 4): ("relatesTo", None),
    }
    harness.corrections = {
        **harness.decisions,
        (1, 2): ("buildsTowards", "first_to_second"),
        (1, 3): ("buildsTowards", "first_to_second"),
    }
    harness.bundle.framework.author = "Synthetic source publisher"
    harness.bundle.framework.provider = "Synthetic source archive"
    harness.bundle.framework.license = "Synthetic license — A\n  B {literal}"
    harness.bundle.framework.attribution_statement = (
        "Synthetic éditeur\n  source {source_attribution_statement} {other}"
    )
    _claims._install(harness=harness, monkeypatch=monkeypatch)
    harness._run()
    final = harness._finalize()
    before = _storage._snapshot(tmp_path)
    source = harness.bundle.model_dump_json()
    calls = list(harness.calls)
    rows = _build(harness)
    assert {str(e.identifier) for e in rows.relationships_builds_towards} == {
        "00249632-9338-52fc-932e-e82cdc7355f5",
        "63f1854a-ebe5-5981-a097-23192667f375",
        "e2947c54-d7ae-5f50-a15b-3fbcf41a2ae5",
    }
    assert [str(e.identifier) for e in rows.relationships_relates_to] == [
        "0f78f128-4795-5cd0-9c20-c10034c4b4f0"
    ]
    assert final.decision_counts == {
        "buildsTowards": 3,
        "relatesTo": 1,
        "no_relation": 1,
        "needs_review": 1,
    }
    for edges in (rows.relationships_builds_towards, rows.relationships_relates_to):
        assert [str(e.identifier) for e in edges] == sorted(
            str(e.identifier) for e in edges
        )
    _assert_metadata(harness=harness, rows=rows)
    assert harness.bundle.model_dump_json() == source
    harness.bundle.items.reverse()
    harness.bundle.relationships_has_child.reverse()
    assert _build(harness).model_dump_json() == rows.model_dump_json()
    assert _storage._snapshot(tmp_path) == before
    assert harness.calls == calls


@pytest.mark.parametrize(
    argnames="decision", argvalues=["empty", "no_relation", "needs_review"]
)
def test_empty_and_nonpublishing_populations_mint_nothing(
    decision: str, monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """Empty and valid ambiguous/negative populations remain distinct from failure.

    Parameters
    ----------
    decision
        Empty nomination or uniform nonpublishing adjudication.
    monkeypatch
        Offline model seam.
    tmp_path
        Isolated artifacts.
    """
    harness = _claims._Harness(count=1 if decision == "empty" else 2, root=tmp_path)
    if decision != "empty":
        harness.default_decision = decision
    _claims._install(harness=harness, monkeypatch=monkeypatch)
    harness._run()
    final = harness._finalize()
    rows = _build(harness)
    assert rows.relationships_builds_towards == rows.relationships_relates_to == ()
    assert rows.relationship_provenance == {}
    assert final.total_claims == (0 if decision == "empty" else 1)
    if decision != "empty":
        assert final.decision_counts[decision] == 1


@pytest.mark.parametrize(argnames="decision", argvalues=["buildsTowards", "relatesTo"])
def test_identity_survives_changed_source_metadata_prompts_and_model(
    decision: str, monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """New material changes provenance while retaining the directly asserted edge ID.

    Parameters
    ----------
    decision
        Public relation held constant across independently regenerated evidence.
    monkeypatch
        Offline model seam and synthetic model identity.
    tmp_path
        Parent of two isolated complete runs.
    """
    identifiers = []
    provenance = []
    for changed in (False, True):
        root = tmp_path / ("changed" if changed else "original")
        harness = _claims._Harness(count=2, root=root)
        harness.decisions[(1, 2)] = (
            decision,
            "first_to_second" if decision == "buildsTowards" else None,
        )
        if changed:
            harness.bundle.framework.license = "Different synthetic source license"
            harness.bundle.framework.attribution_statement = (
                "Different synthetic attribution"
            )
            harness.bundle.items[0].description += " Additional synthetic source text."
            harness.config.learning_progressions.producer_instructions += (
                " Additional synthetic instruction."
            )
            monkeypatch.setattr(
                name="LLM_KG_MODEL", target=Settings, value="openai:gpt-5"
            )
        _claims._install(harness=harness, monkeypatch=monkeypatch)
        harness._run()
        harness._finalize()
        rows = _build(harness)
        _assert_metadata(harness=harness, rows=rows)
        edge = (*rows.relationships_builds_towards, *rows.relationships_relates_to)[0]
        identifiers.append(str(edge.identifier))
        provenance.append(edge.metadata)
    assert (
        identifiers
        == [
            {
                "buildsTowards": "00249632-9338-52fc-932e-e82cdc7355f5",
                "relatesTo": "06d7c270-ce59-57ff-b098-cfa76e85d9a2",
            }[decision]
        ]
        * 2
    )
    for field in (
        "config_content_hash",
        "effective_lp_config_content_hash",
        "final_claims_content_hash",
        "model_configuration_content_hash",
        "requests_content_hash",
        "upstream_content_hash",
    ):
        assert provenance[0][field] != provenance[1][field]


@pytest.mark.parametrize(
    argnames="field",
    argvalues=["approved_by", "attribution_statement_template", "author", "provider"],
)
def test_invalid_runtime_ownership_cannot_bypass_revalidation(
    field: str, monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """Post-load config mutation cannot let callers alter required inference ownership.

    Parameters
    ----------
    field
        Configured ownership field to corrupt after persisted adjudication.
    monkeypatch
        Offline model seam.
    tmp_path
        Isolated evidence directory.
    """
    harness = _claims._Harness(count=2, root=tmp_path)
    harness.default_decision = "relatesTo"
    _claims._install(harness=harness, monkeypatch=monkeypatch)
    harness._run()
    harness._finalize()
    setattr(harness.config.learning_progressions.relationship_metadata, field, "Forged")
    before = _storage._snapshot(tmp_path)
    with pytest.raises(ValueError):
        _build(harness)
    assert _storage._snapshot(tmp_path) == before


@pytest.mark.parametrize(
    argnames="field", argvalues=["attribution_statement", "license"]
)
@pytest.mark.parametrize(argnames="value", argvalues=[None, "", " \n "])
def test_missing_source_ownership_never_gets_a_fallback(
    field: str, monkeypatch: pytest.MonkeyPatch, tmp_path: Path, value: str | None
) -> None:
    """Source license and attribution are mandatory even for mutated model instances.

    Parameters
    ----------
    field
        Required source-framework field.
    monkeypatch
        Offline model seam.
    tmp_path
        Isolated completed evidence.
    value
        Missing or blank upstream value to inject.
    """
    harness = _claims._Harness(count=2, root=tmp_path)
    harness.default_decision = "relatesTo"
    _claims._install(harness=harness, monkeypatch=monkeypatch)
    harness._run()
    harness._finalize()
    setattr(harness.bundle.framework, field, value)
    before = _storage._snapshot(tmp_path)
    with pytest.raises((TypeError, ValueError)):
        _build(harness)
    assert _storage._snapshot(tmp_path) == before


@pytest.mark.parametrize(argnames="profile", argvalues=_PROFILES)
def test_profile_source_and_warning_provenance_survive_minting(
    monkeypatch: pytest.MonkeyPatch, profile: str, tmp_path: Path
) -> None:
    """Tree, DAG, scope-only and unresolved curriculum evidence reaches each row.

    Parameters
    ----------
    monkeypatch
        Offline model seam.
    profile
        Reduced curriculum fixture with synthetic same-grain peers.
    tmp_path
        Isolated evidence directory.
    """
    harness = _claims._Harness(root=tmp_path)
    harness.bundle = _fixtures._expanded_fixture(profile)
    harness.config = _fixtures._config(batch=3, profile=profile)
    harness.default_decision = "relatesTo"
    harness.bundle.framework.license = f"Synthetic {profile} license"
    harness.bundle.framework.attribution_statement = f"Synthetic {profile} attribution"
    _claims._install(harness=harness, monkeypatch=monkeypatch)
    harness._run()
    final = harness._finalize()
    rows = _build(harness)
    assert len(rows.relationships_relates_to) == final.total_claims > 0
    assert not rows.relationships_builds_towards
    _assert_metadata(harness=harness, rows=rows)
    for edge in rows.relationships_relates_to:
        assert edge.source_entity_value < edge.target_entity_value
        candidate = edge.metadata["claim"]["candidate"]
        assert set(candidate["warnings"]) <= set(
            edge.metadata["claim"]["judgment"]["warnings"]
        )
    if profile == "ghana_math":
        assert any(
            e.metadata["claim"]["candidate"]["warnings"]
            for e in rows.relationships_relates_to
        )


@pytest.mark.parametrize(
    argnames="failure",
    argvalues=[
        "cycle",
        "failed_checker",
        "missing_claims",
        "missing_endpoint",
        "self_loop",
        "tampered_claim",
    ],
)
def test_rejected_evidence_cannot_mint_or_modify_relationship_artifacts(
    failure: str, monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """Public minting rejects incomplete, malformed, cyclic, or hand-edited evidence.

    Parameters
    ----------
    failure
        Invalid current input or persisted adjudication state.
    monkeypatch
        Offline model seam.
    tmp_path
        Isolated persisted artifacts.
    """
    harness = _claims._Harness(count=3, root=tmp_path)
    harness.decisions = {
        (1, 2): ("buildsTowards", "first_to_second"),
        (2, 3): ("buildsTowards", "first_to_second"),
    }
    if failure == "cycle":
        harness.decisions[(1, 3)] = ("buildsTowards", "second_to_first")
    if failure == "failed_checker":
        harness.failure = ("verdict", 0)
    _claims._install(harness=harness, monkeypatch=monkeypatch)
    if failure == "failed_checker":
        with pytest.raises(LPGenerationFailed):
            harness._run()
    else:
        harness._run()
        if failure == "cycle":
            with pytest.raises(LPFinalizationCycleError):
                harness._finalize()
        else:
            harness._finalize()
    path = tmp_path / "lp_final_claims.json"
    if failure == "missing_claims":
        path.unlink()
    elif failure == "missing_endpoint":
        harness.bundle.items.pop()
    elif failure in {"self_loop", "tampered_claim"}:
        payload = json.loads(path.read_bytes())
        claim = payload["claims"][0]
        if failure == "self_loop":
            claim["target_sfi_uuid"] = claim["source_sfi_uuid"]
        else:
            claim["judgment"]["rationale"] = "Hand-edited source interpretation."
            claim["provenance"]["judgment_content_hash"] = _claims._hash(
                claim["judgment"]
            )
        payload["content_hash"] = _claims._hash(
            {k: v for k, v in payload.items() if k != "content_hash"}
        )
        path.write_bytes(_storage._bytes(payload))
    before = _storage._snapshot(tmp_path)
    calls = list(harness.calls)
    with pytest.raises(_claims._REJECTIONS):
        _build(harness)
    assert _storage._snapshot(tmp_path) == before
    assert harness.calls == calls


def test_stale_finalization_hash_requires_deterministic_regeneration(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """An earlier source fingerprint cannot authorize rows; regeneration reuses calls.

    Parameters
    ----------
    monkeypatch
        Offline model seam.
    tmp_path
        Isolated prior-source artifact simulation and regenerated evidence.
    """
    harness = _claims._Harness(count=2, root=tmp_path)
    harness.default_decision = "relatesTo"
    _claims._install(harness=harness, monkeypatch=monkeypatch)
    harness._run()
    current = harness._finalize()
    path = tmp_path / "lp_final_claims.json"
    payload = current.model_dump(mode="json")
    payload["finalization_source_content_hash"] = (
        "02081725991093444ff631f0dc09f57420ca0eb685e5560f1e7eeb555905ee09"
    )
    assert (
        payload["finalization_source_content_hash"]
        != current.finalization_source_content_hash
    )
    payload["content_hash"] = _claims._hash(
        {k: v for k, v in payload.items() if k != "content_hash"}
    )
    LPFinalClaims.model_validate(payload)
    path.write_bytes(_storage._bytes(payload))
    before = _storage._snapshot(tmp_path)
    calls = list(harness.calls)
    with pytest.raises(
        expected_exception=ValueError,
        match="differ from current validated adjudication",
    ):
        _build(harness)
    assert _storage._snapshot(tmp_path) == before
    regenerated = harness._finalize()
    assert regenerated == current
    assert (
        regenerated.finalization_source_content_hash
        == hashlib.sha256(Path(lp_finalization.__file__).read_bytes()).hexdigest()
    )
    assert {
        k: v for k, v in _storage._snapshot(tmp_path).items() if k != path.name
    } == {k: v for k, v in before.items() if k != path.name}
    assert _build(harness).relationships_relates_to[0].identifier == UUID(
        "06d7c270-ce59-57ff-b098-cfa76e85d9a2"
    )
    assert harness.calls == calls


@pytest.mark.parametrize(
    argnames=("decision", "direction", "identifier"),
    argvalues=[
        ("buildsTowards", "first_to_second", "00249632-9338-52fc-932e-e82cdc7355f5"),
        ("buildsTowards", "second_to_first", "e897dc91-7e4c-575b-8082-468ff4df28a2"),
        ("relatesTo", None, "06d7c270-ce59-57ff-b098-cfa76e85d9a2"),
    ],
)
def test_uuid_snapshots_distinguish_semantic_direction_and_public_type(
    decision: str,
    direction: str | None,
    identifier: str,
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
) -> None:
    """Identity uses resolved CASE endpoints and relation rather than candidate order.

    Parameters
    ----------
    decision
        Adjudicated public relationship type.
    direction
        Semantic direction independent of technical UUID ordering.
    identifier
        Independently pinned namespace-and-endpoint UUIDv5 value.
    monkeypatch
        Offline model seam.
    tmp_path
        Isolated persisted evidence.
    """
    harness = _claims._Harness(count=2, root=tmp_path)
    harness.decisions[(1, 2)] = (decision, direction)
    _claims._install(harness=harness, monkeypatch=monkeypatch)
    harness._run()
    harness._finalize()
    rows = _build(harness)
    edges = (*rows.relationships_builds_towards, *rows.relationships_relates_to)
    assert len(edges) == 1
    edge = edges[0]
    assert edge.identifier == UUID(identifier)
    assert edge.relationship_type == decision
    assert edge.source_entity_value == str(
        UUID(int=2 if direction == "second_to_first" else 1)
    )
    assert edge.target_entity_value == str(
        UUID(int=1 if direction == "second_to_first" else 2)
    )
    assert edge.metadata["claim"]["provenance"]["checker_outcome"] == "accepted"
    _assert_metadata(harness=harness, rows=rows)
