"""Red-team standalone LP validation against persisted offline evidence."""

# Future Library
from __future__ import annotations

# Standard Library
import hashlib
import json
import socket

from pathlib import Path
from typing import Any
from unittest.mock import Mock
from uuid import UUID, uuid5

# Third Party Library
import pytest

# Package Library
from kgfeg.config import Settings
from kgfeg.kgs import lp_validation
from kgfeg.kgs.lp_finalization import (
    LPFinalClaims,
    LPFinalizationCycleError,
    LPRelationshipProvenance,
    LPRelationships,
    build_lp_relationships,
)
from kgfeg.kgs.lp_validation import LPValidationReport, validate_lp_graph
from kgfeg.kgs.schemas import Relationship
from kgfeg.kgs.utils import KGDirs
from tests.kgfeg.kgs import test_lp_finalization as _claims
from tests.kgfeg.kgs import test_lp_generation as _fixtures
from tests.kgfeg.kgs import test_lp_orchestration as _storage

_DOC_KEY = "synthetic-selection-document"
_FAILURE = "lp_generation_failures.json"
_TEMPLATE = (
    "Learning progression relationship generated by IDinsight using an LLM "
    "producer/checker workflow. Source framework attribution: "
    "{source_attribution_statement}. This inferred relationship was not stated "
    "or endorsed by the source publisher."
)


@pytest.fixture(autouse=True)
def _block_network(monkeypatch: pytest.MonkeyPatch) -> None:
    """Forbid external model transport and pin a non-secret model identity.

    Parameters
    ----------
    monkeypatch
        Restoring network and model-setting substitutions.
    """
    guard = Mock(side_effect=AssertionError("LP validation tests must stay offline."))
    monkeypatch.setattr(name="connect", target=socket.socket, value=guard)
    monkeypatch.setattr(name="connect_ex", target=socket.socket, value=guard)
    monkeypatch.setattr(name="create_connection", target=socket, value=guard)
    monkeypatch.setattr(name="LLM_KG_MODEL", target=Settings, value="openai:gpt-5.2")


def _complete(
    *, harness: _claims._Harness, monkeypatch: pytest.MonkeyPatch
) -> tuple[LPFinalClaims, LPRelationships]:
    """Create a complete offline adjudication and its direct relationship rows.

    Parameters
    ----------
    harness
        Synthetic material and endpoint-keyed producer/checker script.
    monkeypatch
        Offline model seam.

    Returns
    -------
    tuple[LPFinalClaims, LPRelationships]
        Reconstructed final claims and exactly minted direct rows.
    """
    _claims._install(harness=harness, monkeypatch=monkeypatch)
    harness._run()
    final_claims = harness._finalize()
    relationships = build_lp_relationships(
        as_lc_bundle=harness.bundle,
        doc_key=_DOC_KEY,
        kg_config=harness.config,
        kg_dirs=KGDirs(root=harness.root),
    )
    return final_claims, relationships


def _cycle_relationships(
    *, artifact: LPFinalClaims, harness: _claims._Harness
) -> LPRelationships:
    """Build diagnostic input rows independently when public minting rejects cycles.

    Parameters
    ----------
    artifact
        Complete cyclic claim population written for diagnosis.
    harness
        Current source framework, config, and artifact directory.

    Returns
    -------
    LPRelationships
        Exact direct rows with embedded and separately keyed claim provenance.
    """
    framework = harness.bundle.framework
    policy = harness.config.learning_progressions.relationship_metadata
    model_configuration = artifact.execution_material["model_config"]
    model_settings = artifact.execution_material["model_settings"]
    edges: list[Relationship] = []
    provenance_by_id: dict[str, LPRelationshipProvenance] = {}

    for claim in artifact.claims:
        if claim.source_sfi_uuid is None or claim.target_sfi_uuid is None:
            continue

        source = str(claim.source_sfi_uuid)
        target = str(claim.target_sfi_uuid)
        relationship_type = claim.judgment.decision
        identity_key = (
            f"lc:curriculum:{_DOC_KEY}:relationship:{relationship_type}:"
            f"{source}:{target}"
        )
        identifier = uuid5(
            name=identity_key, namespace=Settings.LC_CANONICAL_NAMESPACE_UUID
        )
        provenance = LPRelationshipProvenance(
            approved_by=policy.approved_by,
            attribution_statement_template=policy.attribution_statement_template,
            candidate_artifact_byte_hashes=(
                artifact.request_manifest.artifact_byte_hashes
            ),
            candidate_pairs_content_hash=(
                artifact.request_manifest.candidate_pairs_content_hash
            ),
            candidate_summary_content_hash=(
                artifact.request_manifest.candidate_summary_content_hash
            ),
            claim=claim,
            config_content_hash=artifact.request_manifest.config_content_hash,
            doc_key=_DOC_KEY,
            effective_lp_config_content_hash=_hash(
                harness.config.learning_progressions.model_dump(mode="json")
            ),
            final_claims_content_hash=artifact.content_hash,
            model_configuration=model_configuration,
            model_configuration_content_hash=_hash(model_configuration),
            model_settings=model_settings,
            model_settings_content_hash=_hash(model_settings),
            relationship_identity_key=identity_key,
            requests_content_hash=artifact.request_manifest.requests_content_hash,
            source_framework={
                "attribution_statement": framework.attribution_statement,
                "author": framework.author,
                "case_identifier_uuid": framework.case_identifier_uuid,
                "license": framework.license,
                "provider": framework.provider,
                "title": framework.name,
            },
            upstream_content_hash=artifact.request_manifest.upstream_content_hash,
        )
        edge = Relationship(
            attribution_statement=_TEMPLATE.replace(
                "{source_attribution_statement}", framework.attribution_statement
            ),
            author="LLM generated",
            identifier=identifier,
            license=framework.license,
            metadata=provenance.model_dump(mode="json"),
            provider="IDinsight",
            relationship_type=relationship_type,
            source_entity="StandardsFrameworkItem",
            source_entity_key="case_identifier_uuid",
            source_entity_value=source,
            target_entity="StandardsFrameworkItem",
            target_entity_key="case_identifier_uuid",
            target_entity_value=target,
        )
        edges.append(edge)
        provenance_by_id[str(identifier)] = provenance

    edges.sort(key=lambda edge: str(edge.identifier))
    return LPRelationships(
        final_claims_content_hash=artifact.content_hash,
        relationship_provenance={
            str(edge.identifier): provenance_by_id[str(edge.identifier)]
            for edge in edges
        },
        relationships_builds_towards=tuple(
            edge for edge in edges if edge.relationship_type == "buildsTowards"
        ),
        relationships_relates_to=tuple(
            edge for edge in edges if edge.relationship_type == "relatesTo"
        ),
    )


def _hash(value: Any) -> str:
    """Hash canonical artifact material independently of production helpers.

    Parameters
    ----------
    value
        JSON-compatible material.

    Returns
    -------
    str
        SHA-256 of sorted compact Unicode JSON with its terminal newline.
    """
    return hashlib.sha256(_storage._bytes(value)).hexdigest()


def _report(
    *, harness: _claims._Harness, relationships: LPRelationships
) -> LPValidationReport:
    """Call the public standalone validator with current persisted material.

    Parameters
    ----------
    harness
        Current source bundle, configuration, and artifact directory.
    relationships
        Deterministically minted direct rows and separately keyed provenance.

    Returns
    -------
    LPValidationReport
        Structural/process verdict under test.
    """
    return validate_lp_graph(
        as_lc_bundle=harness.bundle,
        doc_key=_DOC_KEY,
        kg_config=harness.config,
        kg_dirs=KGDirs(root=harness.root),
        relationships=relationships,
    )


def _snapshot(root: Path) -> dict[str, bytes]:
    """Capture every regular file byte without interpreting generated evidence.

    Parameters
    ----------
    root
        Isolated generation directory.

    Returns
    -------
    dict[str, bytes]
        Relative filenames and exact bytes.
    """
    return {
        str(path.relative_to(root)): path.read_bytes()
        for path in sorted(root.rglob("*"))
        if path.is_file()
    }


def test_accepted_direct_graph_passes_with_exact_counts_and_structural_scope(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """Validate every direct outcome without reduction or semantic overclaim.

    Parameters
    ----------
    monkeypatch
        Offline producer/checker seam.
    tmp_path
        Isolated persisted material.
    """
    harness = _claims._Harness(count=4, root=tmp_path)
    harness.decisions = {
        (1, 2): ("buildsTowards", "first_to_second"),
        (1, 3): ("buildsTowards", "first_to_second"),
        (1, 4): ("relatesTo", None),
        (2, 3): ("buildsTowards", "first_to_second"),
        (2, 4): ("no_relation", None),
        (3, 4): ("needs_review", None),
    }
    final_claims, relationships = _complete(harness=harness, monkeypatch=monkeypatch)
    files_before = _snapshot(tmp_path)
    bundle_before = harness.bundle.model_dump_json()
    config_before = harness.config.model_dump_json(by_alias=True)
    relationships_before = relationships.model_dump_json()
    report = _report(harness=harness, relationships=relationships)
    assert report.passed
    assert report.errors == ()
    assert report.warnings == ()
    assert report.object_counts == {
        "builds_towards_claims": 3,
        "builds_towards_relationships": 3,
        "candidate_pairs": 6,
        "final_claims": 6,
        "generation_failure_attempts": 0,
        "identifier_collisions": 0,
        "needs_review_claims": 1,
        "no_relation_claims": 1,
        "relationship_provenance": 4,
        "relates_to_claims": 1,
        "relates_to_relationships": 1,
        "relationships": 4,
        "requests": 2,
        "unresolved_failed_pairs": 0,
        "unresolved_warning_pairs": 0,
    }
    assert {
        (edge.source_entity_value, edge.target_entity_value)
        for edge in relationships.relationships_builds_towards
    } == {
        (str(UUID(int=1)), str(UUID(int=2))),
        (str(UUID(int=1)), str(UUID(int=3))),
        (str(UUID(int=2)), str(UUID(int=3))),
    }
    assert report.input_content_hashes["checkpoint_receipt_bytes"] == (
        final_claims.checkpoint_receipt_byte_hash
    )
    assert report.semantic_validation_performed is False
    assert report.pedagogical_correctness_established is False
    assert "does not establish pedagogical correctness" in report.semantic_scope_notice
    assert LPValidationReport.model_validate_json(report.model_dump_json()) == report
    assert _snapshot(tmp_path) == files_before
    assert harness.bundle.model_dump_json() == bundle_before
    assert harness.config.model_dump_json(by_alias=True) == config_before
    assert relationships.model_dump_json() == relationships_before


@pytest.mark.parametrize(
    argnames="attack", argvalues=["failed_pair", "incomplete_stage", "status"]
)
def test_authenticated_incomplete_checkpoint_or_failure_blocks_success(
    attack: str, monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """Reject authenticated but unsuccessful checkpoint completion state.

    Parameters
    ----------
    attack
        Unresolved pair, incomplete successful prefix, or non-completed receipt state.
    monkeypatch
        Offline producer/checker seam and authenticated checkpoint-state injection.
    tmp_path
        Isolated persisted material.
    """
    harness = _claims._Harness(count=2, root=tmp_path)
    final_claims, relationships = _complete(harness=harness, monkeypatch=monkeypatch)
    receipt_path = tmp_path / "lp_generation_checkpoint_manifest.json"
    failure_path = tmp_path / _FAILURE
    receipt = json.loads(receipt_path.read_bytes())
    failures: list[dict[str, Any]] = []
    if attack == "failed_pair":
        failures = [
            {
                "pair_ids": [final_claims.request_manifest.pair_ids[0]],
                "resolved_run_number": None,
            }
        ]
    elif attack == "incomplete_stage":
        receipt["stage_counts"]["response"] -= 1
    else:
        receipt["status"] = "failed"
    failure_bytes = _storage._bytes(failures)
    failure_path.write_bytes(failure_bytes)
    receipt["artifact_byte_hashes"][_FAILURE] = hashlib.sha256(
        failure_bytes
    ).hexdigest()
    receipt_bytes = _storage._bytes(receipt)
    receipt_path.write_bytes(receipt_bytes)
    injected = final_claims.model_copy(
        deep=True,
        update={
            "checkpoint_receipt_byte_hash": hashlib.sha256(receipt_bytes).hexdigest()
        },
    )
    monkeypatch.setattr(
        name="validate_lp_final_claims_artifact",
        target=lp_validation,
        value=Mock(return_value=injected),
    )
    report = _report(harness=harness, relationships=relationships)
    assert not report.passed
    expected = {
        "failed_pair": "unresolved failed pairs",
        "incomplete_stage": "do not cover every request",
        "status": "not completed with zero failed pairs",
    }[attack]
    assert any(expected in error for error in report.errors)


def test_completed_run_with_resolved_failure_history_passes(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """Resolved retry history remains visible without becoming an unresolved failure.

    Parameters
    ----------
    monkeypatch
        Offline producer/checker seam.
    tmp_path
        Isolated persisted material.
    """
    harness = _claims._Harness(count=2, root=tmp_path)
    harness.default_decision = "no_relation"
    harness.failure = ("verdict", 0)
    _claims._install(harness=harness, monkeypatch=monkeypatch)
    with pytest.raises(_claims.LPGenerationFailed):
        harness._run()
    harness.failure = None
    harness._run()
    harness._finalize()
    relationships = build_lp_relationships(
        as_lc_bundle=harness.bundle,
        doc_key=_DOC_KEY,
        kg_config=harness.config,
        kg_dirs=KGDirs(root=tmp_path),
    )
    report = _report(harness=harness, relationships=relationships)
    failures = json.loads((tmp_path / _FAILURE).read_bytes())
    assert len(failures) == report.object_counts["generation_failure_attempts"] == 1
    assert failures[0]["resolved_run_number"] is not None
    assert report.object_counts["unresolved_failed_pairs"] == 0
    assert report.passed


def test_cycle_diagnostics_cover_every_component_node_edge_and_reference(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """Report all cyclic components and each participating direct claim reference.

    Parameters
    ----------
    monkeypatch
        Offline producer/checker seam.
    tmp_path
        Isolated persisted material.
    """
    harness = _claims._Harness(batch=5, count=7, root=tmp_path)
    harness.decisions = {
        (1, 2): ("buildsTowards", "first_to_second"),
        (1, 3): ("buildsTowards", "second_to_first"),
        (1, 4): ("buildsTowards", "second_to_first"),
        (2, 3): ("buildsTowards", "first_to_second"),
        (3, 4): ("buildsTowards", "first_to_second"),
        (5, 6): ("buildsTowards", "first_to_second"),
        (5, 7): ("buildsTowards", "second_to_first"),
        (6, 7): ("buildsTowards", "first_to_second"),
    }
    _claims._install(harness=harness, monkeypatch=monkeypatch)
    harness._run()
    with pytest.raises(LPFinalizationCycleError) as caught:
        harness._finalize()
    relationships = _cycle_relationships(
        artifact=caught.value.artifact, harness=harness
    )
    report = _report(harness=harness, relationships=relationships)
    diagnostics = report.cycle_diagnostics
    assert not report.passed
    assert diagnostics.cyclic_component_count == 2
    assert diagnostics.cyclic_node_count == 7
    assert diagnostics.cyclic_edge_count == 8
    assert diagnostics.graph_edge_count == 8
    assert {
        tuple(node.int for node in component.node_uuids)
        for component in diagnostics.components
    } == {
        (1, 2, 3, 4),
        (5, 6, 7),
    }
    expected_edge_counts = {(1, 2, 3, 4): 5, (5, 6, 7): 3}
    diagnostic_ids = {
        edge.relationship_id
        for component in diagnostics.components
        for edge in component.edges
    }
    rows_by_id = {
        edge.identifier: edge for edge in relationships.relationships_builds_towards
    }
    assert diagnostic_ids == {
        edge.identifier for edge in relationships.relationships_builds_towards
    }
    for component in diagnostics.components:
        node_ids = tuple(node.int for node in component.node_uuids)
        assert (
            component.edge_count
            == len(component.edges)
            == expected_edge_counts[node_ids]
        )
        assert component.node_count == len(component.node_uuids) == len(node_ids)
        assert component.representative_cycle[0] == component.representative_cycle[-1]
        assert len(component.representative_relationship_ids) == (
            len(component.representative_cycle) - 1
        )
        assert set(component.representative_relationship_ids) <= diagnostic_ids
        for source, target, relationship_id in zip(
            component.representative_cycle,
            component.representative_cycle[1:],
            component.representative_relationship_ids,
        ):
            row = rows_by_id[relationship_id]
            assert row.source_entity_value == str(source)
            assert row.target_entity_value == str(target)
        for edge in component.edges:
            claim = relationships.relationship_provenance[
                str(edge.relationship_id)
            ].claim
            provenance = claim.provenance
            assert edge.pair_id == claim.judgment.pair_id
            assert edge.request_id is not None
            assert edge.producer_checkpoint_content_hash is not None
            assert edge.checker_checkpoint_content_hash is not None
            assert edge.response_checkpoint_content_hash is not None
            assert edge.request_id == provenance.request_id
            assert (
                edge.producer_checkpoint_content_hash
                == provenance.producer_checkpoint_content_hash
            )
            assert (
                edge.checker_checkpoint_content_hash
                == provenance.checker_checkpoint_content_hash
            )
            assert (
                edge.response_checkpoint_content_hash
                == provenance.response_checkpoint_content_hash
            )
    assert any(
        len(component.representative_relationship_ids) < component.edge_count
        for component in diagnostics.components
    )
    assert any("2 cyclic components" in error for error in report.errors)
    reversed_relationships = relationships.model_copy(
        deep=True,
        update={
            "relationship_provenance": dict(
                reversed(tuple(relationships.relationship_provenance.items()))
            ),
            "relationships_builds_towards": tuple(
                reversed(relationships.relationships_builds_towards)
            ),
        },
    )
    reversed_report = _report(harness=harness, relationships=reversed_relationships)
    assert reversed_report.cycle_diagnostics == diagnostics


@pytest.mark.parametrize(
    argnames="attack",
    argvalues=["extra_closure", "missing_direct", "second_relation"],
)
def test_direct_claim_alignment_and_logical_pair_exclusivity_are_enforced(
    attack: str, monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """Reject reachability edges, omitted direct claims, and a second pair relation.

    Parameters
    ----------
    attack
        Closure, reduction, or mutually exclusive relationship mutation.
    monkeypatch
        Offline producer/checker seam.
    tmp_path
        Isolated persisted material.
    """
    harness = _claims._Harness(count=3, root=tmp_path)
    harness.decisions = {
        (1, 2): ("buildsTowards", "first_to_second"),
        (2, 3): ("buildsTowards", "first_to_second"),
    }
    _, relationships = _complete(harness=harness, monkeypatch=monkeypatch)
    builds = list(relationships.relationships_builds_towards)
    relates = list(relationships.relationships_relates_to)
    if attack == "missing_direct":
        builds.pop()
    else:
        basis = builds[0]
        if attack == "extra_closure":
            source, target, relationship_type = (
                UUID(int=1),
                UUID(int=3),
                "buildsTowards",
            )
        else:
            source, target, relationship_type = UUID(int=1), UUID(int=2), "relatesTo"
        extra = basis.model_copy(
            deep=True,
            update={
                "identifier": UUID(int=800 if attack == "extra_closure" else 801),
                "relationship_type": relationship_type,
                "source_entity_value": str(source),
                "target_entity_value": str(target),
            },
        )
        if attack == "extra_closure":
            builds.append(extra)
        else:
            relates.append(extra)
    attacked = relationships.model_copy(
        deep=True,
        update={
            "relationships_builds_towards": tuple(builds),
            "relationships_relates_to": tuple(relates),
        },
    )
    report = _report(harness=harness, relationships=attacked)
    assert not report.passed
    assert any(
        "accepted-claim, relationship, or provenance counts disagree" in error
        for error in report.errors
    )
    if attack == "second_relation":
        assert any(
            "logical pairs publish duplicate or mutually exclusive rows" in error
            for error in report.errors
        )
    else:
        assert any(
            "complete directly accepted claim population" in error
            for error in report.errors
        )


@pytest.mark.parametrize(
    argnames="attack",
    argvalues=[
        "attribution",
        "author",
        "embedded_provenance",
        "final_claims_hash",
        "license",
        "matched_approved_by_forgery",
        "matched_attribution_template_forgery",
        "matched_provenance_forgery",
        "missing_provenance_key",
        "provider",
        "separate_provenance_hash",
    ],
)
def test_exact_ownership_endpoint_keys_and_provenance_are_required(  # pylint: disable=R0915
    attack: str, monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """Require exact inherited ownership and complete duplicate provenance views.

    Parameters
    ----------
    attack
        Relationship or provenance field to corrupt.
    monkeypatch
        Offline producer/checker seam.
    tmp_path
        Isolated persisted material.
    """
    harness = _claims._Harness(count=2, root=tmp_path)
    harness.default_decision = "relatesTo"
    _, relationships = _complete(harness=harness, monkeypatch=monkeypatch)
    edge = relationships.relationships_relates_to[0]
    provenance = relationships.relationship_provenance[str(edge.identifier)]
    expected_keys = {
        "approved_by",
        "attribution_statement_template",
        "candidate_artifact_byte_hashes",
        "candidate_pairs_content_hash",
        "candidate_summary_content_hash",
        "claim",
        "config_content_hash",
        "doc_key",
        "effective_lp_config_content_hash",
        "final_claims_content_hash",
        "model_configuration",
        "model_configuration_content_hash",
        "model_settings",
        "model_settings_content_hash",
        "relationship_identity_key",
        "requests_content_hash",
        "source_framework",
        "upstream_content_hash",
    }
    assert edge.author == "LLM generated"
    assert edge.provider == "IDinsight"
    assert edge.license == harness.bundle.framework.license
    assert edge.attribution_statement == _TEMPLATE.replace(
        "{source_attribution_statement}",
        harness.bundle.framework.attribution_statement,
    )
    assert edge.source_entity == edge.target_entity == "StandardsFrameworkItem"
    assert edge.source_entity_key == edge.target_entity_key == "case_identifier_uuid"
    assert edge.metadata == provenance.model_dump(mode="json")
    assert set(edge.metadata) == expected_keys

    updates: dict[str, Any] = {}
    provenance_by_id = dict(relationships.relationship_provenance)
    if attack == "attribution":
        updates["attribution_statement"] = "Source publisher authored this inference."
    elif attack == "author":
        updates["author"] = "Synthetic source publisher"
    elif attack == "embedded_provenance":
        updates["metadata"] = {}
    elif attack == "final_claims_hash":
        attacked = relationships.model_copy(
            deep=True, update={"final_claims_content_hash": "0" * 64}
        )
        report = _report(harness=harness, relationships=attacked)
        assert not report.passed
        assert any(
            "stale or different final claims" in error for error in report.errors
        )
        return
    elif attack == "license":
        updates["license"] = "Forged license"
    elif attack in {
        "matched_approved_by_forgery",
        "matched_attribution_template_forgery",
    }:
        field, forged_value = {
            "matched_approved_by_forgery": ("approved_by", "Forged approver"),
            "matched_attribution_template_forgery": (
                "attribution_statement_template",
                "Forged attribution template.",
            ),
        }[attack]
        forged_provenance = provenance.model_copy(
            deep=True, update={field: forged_value}
        )
        provenance_by_id[str(edge.identifier)] = forged_provenance
        updates["metadata"] = forged_provenance.model_dump(mode="json")
    elif attack == "matched_provenance_forgery":
        forged_source_framework = provenance.source_framework.model_copy(
            deep=True, update={"license": "Forged source license"}
        )
        forged_provenance = provenance.model_copy(
            deep=True, update={"source_framework": forged_source_framework}
        )
        provenance_by_id[str(edge.identifier)] = forged_provenance
        updates["metadata"] = forged_provenance.model_dump(mode="json")
    elif attack == "missing_provenance_key":
        provenance_by_id.clear()
    elif attack == "provider":
        updates["provider"] = "Source archive"
    else:
        provenance_by_id[str(edge.identifier)] = provenance.model_copy(
            deep=True, update={"requests_content_hash": "0" * 64}
        )
    attacked_edge = edge.model_copy(deep=True, update=updates)
    attacked = relationships.model_copy(
        deep=True,
        update={
            "relationship_provenance": provenance_by_id,
            "relationships_relates_to": (attacked_edge,),
        },
    )
    report = _report(harness=harness, relationships=attacked)
    assert not report.passed
    assert any(
        "ownership metadata" in error
        or "provenance" in error
        or "provenance keys" in error
        for error in report.errors
    )


def test_failed_upstream_bundle_cannot_validate_successfully(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """Reject an authoritative AS+LC bundle whose own validation failed.

    Parameters
    ----------
    monkeypatch
        Offline producer/checker seam and authenticated-claim injection boundary.
    tmp_path
        Isolated persisted material.
    """
    harness = _claims._Harness(count=2, root=tmp_path)
    final_claims, relationships = _complete(harness=harness, monkeypatch=monkeypatch)
    harness.bundle.validation_report = harness.bundle.validation_report.model_copy(
        deep=True,
        update={
            "errors": ["Injected upstream structural failure."],
            "passed": False,
        },
    )
    monkeypatch.setattr(
        name="validate_lp_final_claims_artifact",
        target=lp_validation,
        value=Mock(return_value=final_claims),
    )
    with pytest.raises(
        expected_exception=ValueError,
        match="requires a passed, error-free AS\\+LC validation report",
    ):
        _report(harness=harness, relationships=relationships)


def test_final_claim_count_must_equal_the_candidate_population(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """Independently reconcile final-claim count with all nominated candidates.

    Parameters
    ----------
    monkeypatch
        Offline producer/checker seam and authenticated-claim injection boundary.
    tmp_path
        Isolated persisted material.
    """
    harness = _claims._Harness(count=3, root=tmp_path)
    final_claims, relationships = _complete(harness=harness, monkeypatch=monkeypatch)
    attacked = final_claims.model_copy(
        deep=True, update={"claims": final_claims.claims[:-1]}
    )
    monkeypatch.setattr(
        name="validate_lp_final_claims_artifact",
        target=lp_validation,
        value=Mock(return_value=attacked),
    )
    report = _report(harness=harness, relationships=relationships)
    assert not report.passed
    assert (
        "LP final-claim count does not match the candidate population." in report.errors
    )


@pytest.mark.parametrize(
    argnames="attack",
    argvalues=[
        "duplicate_id",
        "identity",
        "noncanonical_relates_to",
        "self_loop",
        "unknown_endpoint",
        "unsupported_relation",
        "wrong_endpoint_key",
        "wrong_entity_type",
    ],
)
def test_graph_shape_identity_duplicates_and_collisions_are_rejected(
    attack: str, monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """Reject malformed rows even when their generic relationship schema is valid.

    Parameters
    ----------
    attack
        Intrinsic row, identity, pair, endpoint, or graph collision mutation.
    monkeypatch
        Offline producer/checker seam.
    tmp_path
        Isolated persisted material.
    """
    harness = _claims._Harness(count=2, root=tmp_path)
    harness.default_decision = "relatesTo"
    _, relationships = _complete(harness=harness, monkeypatch=monkeypatch)
    edge = relationships.relationships_relates_to[0]
    rows = [edge]
    updates: dict[str, Any] = {}
    expected = ""
    if attack == "duplicate_id":
        rows.append(edge.model_copy(deep=True))
        expected = "identifiers are duplicated"
    elif attack == "identity":
        updates["identifier"] = UUID(int=700)
        expected = "complete directly accepted claim population"
    elif attack == "noncanonical_relates_to":
        updates.update(
            source_entity_value=edge.target_entity_value,
            target_entity_value=edge.source_entity_value,
        )
        expected = "not in canonical endpoint order"
    elif attack == "self_loop":
        updates["target_entity_value"] = edge.source_entity_value
        expected = "self-loop"
    elif attack == "unknown_endpoint":
        updates["target_entity_value"] = str(UUID(int=999))
        expected = "unknown SFI endpoint"
    elif attack == "unsupported_relation":
        updates["relationship_type"] = "recurring_practice"
        expected = "differs from its deterministic identity"
    elif attack == "wrong_endpoint_key":
        updates["source_entity_key"] = "identifier"
        expected = "differs from its deterministic identity"
    else:
        updates["source_entity"] = "LearningComponent"
        expected = "differs from its deterministic identity"
    rows[0] = edge.model_copy(deep=True, update=updates)
    attacked = relationships.model_copy(
        deep=True, update={"relationships_relates_to": tuple(rows)}
    )
    if attack in {
        "self_loop",
        "unsupported_relation",
        "wrong_endpoint_key",
        "wrong_entity_type",
    }:
        expected_schema_error = {
            "self_loop": "cannot connect an entity to itself",
            "unsupported_relation": "Unsupported relationshipType",
            "wrong_endpoint_key": "must use case_identifier_uuid endpoints",
            "wrong_entity_type": (
                "must be StandardsFrameworkItem -> StandardsFrameworkItem"
            ),
        }[attack]
        with pytest.raises(ValueError, match=expected_schema_error):
            _report(harness=harness, relationships=attacked)
        return
    report = _report(harness=harness, relationships=attacked)
    assert not report.passed
    assert any(expected in error for error in report.errors)


@pytest.mark.parametrize(
    argnames="category",
    argvalues=["framework", "has_child", "learning_component", "sfi", "supports"],
)
def test_graph_wide_identifier_collisions_cover_every_upstream_category(
    category: str, monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """Reject an LP relationship identifier reused by any upstream entity category.

    Parameters
    ----------
    category
        Framework, SFI, LC, hierarchy, or support identifier to reuse.
    monkeypatch
        Offline producer/checker seam.
    tmp_path
        Isolated persisted material.
    """
    harness = _claims._Harness(batch=20, root=tmp_path)
    harness.bundle = _fixtures._expanded_fixture("ghana_math")
    harness.config = _fixtures._config(batch=20, profile="ghana_math")
    harness.default_decision = "relatesTo"
    _, relationships = _complete(harness=harness, monkeypatch=monkeypatch)
    collision_id = {
        "framework": harness.bundle.framework.case_identifier_uuid,
        "has_child": harness.bundle.relationships_has_child[0].identifier,
        "learning_component": harness.bundle.learning_components[0].identifier,
        "sfi": harness.bundle.items[0].case_identifier_uuid,
        "supports": harness.bundle.relationships_supports[0].identifier,
    }[category]
    rows = list(relationships.relationships_relates_to)
    rows[0] = rows[0].model_copy(deep=True, update={"identifier": collision_id})
    attacked = relationships.model_copy(
        deep=True, update={"relationships_relates_to": tuple(rows)}
    )
    report = _report(harness=harness, relationships=attacked)
    assert not report.passed
    assert report.object_counts["identifier_collisions"] == 1
    assert any(
        "graph contains identifier collisions" in error and str(collision_id) in error
        for error in report.errors
    )


@pytest.mark.parametrize(argnames="attack", argvalues=["coordinate", "statement_type"])
def test_policy_is_recomputed_from_current_closed_world_and_local_order_inputs(
    attack: str, monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """Reapply current statement-type and coordinate policy to every final claim.

    Parameters
    ----------
    attack
        Current upstream field that makes the authenticated prior claim inadmissible.
    monkeypatch
        Offline model seam and final-claim injection boundary.
    tmp_path
        Isolated persisted material.
    """
    harness = _claims._Harness(count=2, root=tmp_path)
    harness.decisions[(1, 2)] = ("buildsTowards", "first_to_second")
    final_claims, relationships = _complete(harness=harness, monkeypatch=monkeypatch)
    monkeypatch.setattr(
        name="validate_lp_final_claims_artifact",
        target=lp_validation,
        value=Mock(return_value=final_claims),
    )
    if attack == "coordinate":
        harness.bundle.items[0].metadata["identity_scope_values"][
            "Grade"
        ] = "PRIMARY THREE"
    else:
        harness.bundle.items[0].statement_type = "Topic"
    report = _report(harness=harness, relationships=relationships)
    assert not report.passed
    assert any(
        "excluded by current policy" in error
        or "disagrees with pair permissions" in error
        for error in report.errors
    )


def test_report_rejects_false_pass_semantic_proof_and_independent_semantic_checks(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """Make structural validity incapable of claiming pedagogical correctness.

    Parameters
    ----------
    monkeypatch
        Offline producer/checker seam.
    tmp_path
        Isolated persisted material.
    """
    harness = _claims._Harness(count=2, root=tmp_path)
    _, relationships = _complete(harness=harness, monkeypatch=monkeypatch)
    report = _report(harness=harness, relationships=relationships)
    assert report.passed
    assert not any("semantic_quality" in check for check in report.validation_checks)
    for attack in (
        "false_pass",
        "pedagogical_proof",
        "scope_claim",
        "semantic_check",
        "semantic_performed",
    ):
        payload = report.model_dump(mode="json")
        if attack == "false_pass":
            payload["errors"] = ["Injected structural error."]
            payload["passed"] = True
        elif attack == "pedagogical_proof":
            payload["pedagogical_correctness_established"] = True
        elif attack == "scope_claim":
            payload["semantic_scope_notice"] = (
                "Structural validity establishes pedagogical correctness."
            )
        elif attack == "semantic_check":
            payload["validation_checks"].append("semantic_quality_gate")
        else:
            payload["semantic_validation_performed"] = True
        material = {
            key: value for key, value in payload.items() if key != "content_hash"
        }
        payload["content_hash"] = _hash(material)
        with pytest.raises(ValueError):
            LPValidationReport.model_validate(payload)


@pytest.mark.parametrize(
    argnames="filename",
    argvalues=[
        "lp_candidate_pairs.jsonl",
        "lp_candidate_summary.json",
        "lp_final_claims.json",
        "lp_generation_checkpoint_manifest.json",
        "lp_generation_draft_responses.jsonl",
        "lp_generation_failures.json",
        "lp_generation_requests.jsonl",
        "lp_generation_requests_manifest.json",
        "lp_generation_responses.jsonl",
        "lp_generation_validation_verdicts.jsonl",
    ],
)
def test_stale_persisted_inputs_manifests_receipts_claims_and_checkpoints_are_rejected(
    filename: str, monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """Reject one-byte changes throughout the authenticated material chain.

    Parameters
    ----------
    filename
        Persisted input, manifest, receipt, claim, failure, or checkpoint to change.
    monkeypatch
        Offline producer/checker seam.
    tmp_path
        Isolated persisted material.
    """
    harness = _claims._Harness(count=2, root=tmp_path)
    _, relationships = _complete(harness=harness, monkeypatch=monkeypatch)
    path = tmp_path / filename
    path.write_bytes(path.read_bytes() + b" ")
    attacked = _snapshot(tmp_path)
    with pytest.raises(_claims._REJECTIONS):
        _report(harness=harness, relationships=relationships)
    assert _snapshot(tmp_path) == attacked


@pytest.mark.parametrize(argnames="attack", argvalues=["candidate", "judgment"])
def test_unresolved_warning_tampering_is_rejected(
    attack: str, monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """Reject removal of required unresolved context from either claim view.

    Parameters
    ----------
    attack
        Candidate or reconciled judgment warning view to clear.
    monkeypatch
        Offline producer/checker seam and authenticated-claim injection boundary.
    tmp_path
        Isolated persisted material.
    """
    harness = _claims._Harness(root=tmp_path)
    harness.bundle = _fixtures._expanded_fixture("ghana_math")
    harness.config = _fixtures._config(batch=4, profile="ghana_math")
    harness.default_decision = "needs_review"
    final_claims, relationships = _complete(harness=harness, monkeypatch=monkeypatch)
    claims = list(final_claims.claims)
    claim_index = next(
        index for index, claim in enumerate(claims) if claim.candidate.warnings
    )
    claim = claims[claim_index]
    update = {
        attack: getattr(claim, attack).model_copy(deep=True, update={"warnings": ()})
    }
    claims[claim_index] = claim.model_copy(deep=True, update=update)
    attacked = final_claims.model_copy(deep=True, update={"claims": tuple(claims)})
    monkeypatch.setattr(
        name="validate_lp_final_claims_artifact",
        target=lp_validation,
        value=Mock(return_value=attacked),
    )
    report = _report(harness=harness, relationships=relationships)
    assert not report.passed
    assert any(
        claim.judgment.pair_id in error
        and "disagrees with pair permissions or required warnings" in error
        for error in report.errors
    )


def test_unresolved_warnings_and_needs_review_remain_visible_and_nonpublishing(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """Preserve unresolved-context warnings while ambiguous claims emit no edge.

    Parameters
    ----------
    monkeypatch
        Offline producer/checker seam.
    tmp_path
        Isolated persisted material.
    """
    harness = _claims._Harness(root=tmp_path)
    harness.bundle = _fixtures._expanded_fixture("ghana_math")
    harness.config = _fixtures._config(batch=4, profile="ghana_math")
    harness.default_decision = "needs_review"
    final_claims, relationships = _complete(harness=harness, monkeypatch=monkeypatch)
    report = _report(harness=harness, relationships=relationships)
    warned = [claim for claim in final_claims.claims if claim.candidate.warnings]
    assert report.passed
    assert warned
    assert final_claims.decision_counts["needs_review"] == len(final_claims.claims)
    assert relationships.relationships_builds_towards == ()
    assert relationships.relationships_relates_to == ()
    assert relationships.relationship_provenance == {}
    assert report.object_counts["needs_review_claims"] == len(final_claims.claims)
    assert report.object_counts["unresolved_warning_pairs"] == len(warned)
    assert len(report.warnings) == len(warned)
    for claim in warned:
        assert set(claim.candidate.warnings) <= set(claim.judgment.warnings)
        assert any(claim.judgment.pair_id in warning for warning in report.warnings)


def test_validator_is_read_only_and_never_repairs_forged_relationships(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """Return errors without deleting, converting, or patching supplied edge data.

    Parameters
    ----------
    monkeypatch
        Offline producer/checker seam.
    tmp_path
        Isolated persisted material.
    """
    harness = _claims._Harness(count=2, root=tmp_path)
    harness.default_decision = "relatesTo"
    _, relationships = _complete(harness=harness, monkeypatch=monkeypatch)
    edge = relationships.relationships_relates_to[0]
    forged = edge.model_copy(
        deep=True,
        update={
            "identifier": UUID(int=999),
            "relationship_type": "buildsTowards",
        },
    )
    attacked = relationships.model_copy(
        deep=True,
        update={"relationships_builds_towards": (forged,)},
    )
    files_before = _snapshot(tmp_path)
    bundle_before = harness.bundle.model_dump_json()
    attacked_before = attacked.model_dump_json()
    report = _report(harness=harness, relationships=attacked)
    assert not report.passed
    assert len(attacked.relationships_builds_towards) == 1
    assert len(attacked.relationships_relates_to) == 1
    assert attacked.model_dump_json() == attacked_before
    assert harness.bundle.model_dump_json() == bundle_before
    assert _snapshot(tmp_path) == files_before


def test_validator_rehashes_checkpoint_receipt_after_final_claim_reconstruction(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """Reject a receipt swap occurring after final claims are authenticated.

    Parameters
    ----------
    monkeypatch
        Offline producer/checker seam and post-reconstruction race injection.
    tmp_path
        Isolated persisted material.
    """
    harness = _claims._Harness(count=2, root=tmp_path)
    _, relationships = _complete(harness=harness, monkeypatch=monkeypatch)
    original = lp_validation.validate_lp_final_claims_artifact
    receipt_name = "lp_generation_checkpoint_manifest.json"
    receipt_path = tmp_path / receipt_name
    before = _snapshot(tmp_path)
    tampered = receipt_path.read_bytes() + b" "

    def _reconstruct_then_tamper(**kwargs: Any) -> LPFinalClaims:
        """Swap only the receipt bytes after ordinary reconstruction returns.

        Parameters
        ----------
        kwargs
            Exact final-claim validation arguments.

        Returns
        -------
        LPFinalClaims
            Authenticated claims whose receipt predates the injected file swap.
        """
        artifact = original(**kwargs)
        receipt_path.write_bytes(tampered)
        return artifact

    monkeypatch.setattr(
        name="validate_lp_final_claims_artifact",
        target=lp_validation,
        value=_reconstruct_then_tamper,
    )
    with pytest.raises(
        expected_exception=ValueError,
        match="checkpoint receipt differs from final claims",
    ):
        _report(harness=harness, relationships=relationships)
    after = _snapshot(tmp_path)
    assert after[receipt_name] == tampered
    assert {key: value for key, value in after.items() if key != receipt_name} == {
        key: value for key, value in before.items() if key != receipt_name
    }


def test_validator_rehashes_failure_artifact_after_final_claim_reconstruction(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """Reject a failure-file swap occurring after final claims are authenticated.

    Parameters
    ----------
    monkeypatch
        Offline producer/checker seam and post-reconstruction race injection.
    tmp_path
        Isolated persisted material.
    """
    harness = _claims._Harness(count=2, root=tmp_path)
    _, relationships = _complete(harness=harness, monkeypatch=monkeypatch)
    original = lp_validation.validate_lp_final_claims_artifact
    before = _snapshot(tmp_path)
    tampered = _storage._bytes([{"pair_ids": ["stale-or-forged-pair"]}])

    def _reconstruct_then_tamper(**kwargs: Any) -> LPFinalClaims:
        """Swap only the failure bytes after the ordinary reconstruction returns.

        Parameters
        ----------
        kwargs
            Exact final-claim validation arguments.

        Returns
        -------
        LPFinalClaims
            Authenticated claims whose receipt predates the injected file swap.
        """
        artifact = original(**kwargs)
        (tmp_path / _FAILURE).write_bytes(tampered)
        return artifact

    monkeypatch.setattr(
        name="validate_lp_final_claims_artifact",
        target=lp_validation,
        value=_reconstruct_then_tamper,
    )
    with pytest.raises(
        expected_exception=ValueError,
        match="failure artifact differs from the checkpoint receipt",
    ):
        _report(harness=harness, relationships=relationships)
    after = _snapshot(tmp_path)
    assert after[_FAILURE] == tampered
    assert {key: value for key, value in after.items() if key != _FAILURE} == {
        key: value for key, value in before.items() if key != _FAILURE
    }


def test_validator_rejects_transaction_created_after_final_claim_reconstruction(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """Reject an unfinished transaction created after claims are authenticated.

    Parameters
    ----------
    monkeypatch
        Offline producer/checker seam and post-reconstruction race injection.
    tmp_path
        Isolated persisted material.
    """
    harness = _claims._Harness(count=2, root=tmp_path)
    _, relationships = _complete(harness=harness, monkeypatch=monkeypatch)
    original = lp_validation.validate_lp_final_claims_artifact
    before = _snapshot(tmp_path)
    transaction_name = "lp_generation_checkpoint_transaction.json"
    transaction_bytes = _storage._bytes({"status": "unfinished"})

    def _reconstruct_then_create_transaction(**kwargs: Any) -> LPFinalClaims:
        """Create a transaction only after ordinary reconstruction succeeds.

        Parameters
        ----------
        kwargs
            Exact final-claim validation arguments.

        Returns
        -------
        LPFinalClaims
            Authenticated claims that predate the injected transaction.
        """
        artifact = original(**kwargs)
        (tmp_path / transaction_name).write_bytes(transaction_bytes)
        return artifact

    monkeypatch.setattr(
        name="validate_lp_final_claims_artifact",
        target=lp_validation,
        value=_reconstruct_then_create_transaction,
    )
    with pytest.raises(
        expected_exception=ValueError,
        match="checkpoint transaction is unfinished",
    ):
        _report(harness=harness, relationships=relationships)
    after = _snapshot(tmp_path)
    assert after[transaction_name] == transaction_bytes
    assert {
        key: value for key, value in after.items() if key != transaction_name
    } == before
