authors:
  Tony Zhao:
    name: Tony Zhao
    description: Senior Data Scientist
    avatar: https://raw.githubusercontent.com/IDinsight/user-profiles/main/docs/images/author-avatars/tony.png
  Mustafa Akolawala:
    name: Mustafa Akolawala
    description: Full Stack Data Scientist
    avatar: https://raw.githubusercontent.com/IDinsight/user-profiles/main/docs/images/author-avatars/mustafa.png
