"""Test Learning Progressions policy wiring against Academic Standards configs."""

# Standard Library
import json

from copy import deepcopy
from itertools import permutations
from pathlib import Path
from typing import Any

# Third Party Library
import pytest

from pydantic import ValidationError

# Package Library
from kgfeg.schemas import RunConfig
from tests.constants import PACKAGE_PATH, PARAM

_APPROVED_ATTRIBUTION_TEMPLATE = (
    "Learning progression relationship generated by IDinsight using an LLM "
    "producer/checker workflow. Source framework attribution: "
    "{source_attribution_statement}. This inferred relationship was not stated or "
    "endorsed by the source publisher."
)
_COMMON_CANDIDATE_POLICY = {
    "budgets": {
        "max_candidates_per_sfi": 12,
        "max_total_candidates": 5000,
    }
}
_COMMON_EVIDENCE_LIMITS = {
    "max_ancestor_path_depth": 8,
    "max_ancestor_paths_per_sfi": 4,
    "max_learning_components_per_sfi": 8,
    "max_source_evidence_characters_per_sfi": 2000,
    "max_source_evidence_items_per_sfi": 4,
}
_COMMON_RELATIONSHIP_METADATA = {
    "approved_by": "IDinsight",
    "attribution_statement_template": _APPROVED_ATTRIBUTION_TEMPLATE,
    "author": "LLM generated",
    "provider": "IDinsight",
}
_COMMON_RETRY_POLICY = {
    "checker_max_retries": 2,
    "producer_max_retries": 2,
}
_PROFILE_CONFIG_PATHS: dict[str, Path] = {
    "ghana_english": PACKAGE_PATH / "examples/ghana/config_english_curriculum.json",
    "ghana_math": PACKAGE_PATH / "examples/ghana/config_math_curriculum.json",
    "madhi_math": PACKAGE_PATH / "examples/india/madhi/config_math.json",
    "nigeria_math": (PACKAGE_PATH / "examples/nigeria/config_math_curriculum_1_3.json"),
    "pratham_science": PACKAGE_PATH / "examples/india/pratham/config_science.json",
    "rwanda_math": (PACKAGE_PATH / "examples/rwanda/config_math_curriculum_p1_p3.json"),
}
_PROFILE_COORDINATES: dict[str, tuple[str, tuple[str, ...]]] = {
    "ghana_english": ("Grade", ("BASIC 1", "BASIC 2", "BASIC 3")),
    "ghana_math": ("Grade", ("BASIC 4", "BASIC 5", "BASIC 6")),
    "madhi_math": (
        "Class",
        ("Class-1", "Class-2", "Class-3", "Class-4", "Class-5"),
    ),
    "nigeria_math": (
        "Grade",
        ("PRIMARY ONE", "PRIMARY TWO", "PRIMARY THREE"),
    ),
    "pratham_science": ("Class", ("Class IX", "Class X")),
    "rwanda_math": ("Grade", ("P1", "P2", "P3")),
}
_PROFILE_INSTRUCTIONS: dict[str, tuple[str, str]] = {
    "ghana_english": (
        "Independently check Content Standard and Indicator judgments only within "
        "their respective grains and the BASIC 1 through BASIC 3 order. In this "
        "spiralled curriculum, require substantive extension for buildsTowards, "
        "meaningful reinforcement without dependency for relatesTo, and no_relation "
        "for generic repetition; preserve unresolved-placement warnings and reject "
        "claims based only on shared wording, hierarchy, or Learning Components.",
        "Judge Content Standard pairs and Indicator pairs only within the same "
        "statement-type grain. Use the configured BASIC 1 through BASIC 3 sequence "
        "for developmental direction and source-backed Strand, Sub-Strand, statement "
        "text, and Learning Components as evidence. The curriculum deliberately "
        "recurs: distinguish expanded capability from meaningful reinforcement and "
        "from generic repetition without inferring progression from repeated wording "
        "alone.",
    ),
    "ghana_math": (
        "Independently check Content Standard and Indicator judgments only within "
        "their respective grains and the BASIC 4 through BASIC 6 order. Treat known "
        "source-code anomalies and unresolved hierarchy warnings as audit context, "
        "never as positive placement evidence; reject cross-grain claims, reversed "
        "development, and claims based only on shared codes, hierarchy, wording, or "
        "Learning Components.",
        "Judge Content Standard pairs and Indicator pairs only within the same "
        "statement-type grain. Use the configured BASIC 4 through BASIC 6 sequence "
        "for developmental direction and use trustworthy Strand, Sub-Strand, "
        "statement text, and Learning Components as bounded evidence. Preserve "
        "code-anomaly and unresolved-placement warnings, and never treat a "
        "framework-root fallback or source code as positive hierarchy evidence.",
    ),
    "madhi_math": (
        "Independently check Content-to-Content judgments against the source-backed "
        "Curricular Goal and Competency context and the configured Class-1 through "
        "Class-5 order. Reject a developmental direction that reverses that order, "
        "treats a shared Competency or Learning Component as sufficient by itself, "
        "or turns a repeated topic into progression without a substantive extension.",
        "Judge only pairs of Content SFIs. Use the configured Class-1 through Class-5 "
        "sequence for developmental direction and use source-backed Curricular Goal, "
        "Competency, Content text, and Learning Components as evidence. Distinguish "
        "substantive extension from meaningful same-topic recurrence and generic "
        "repetition; shared hierarchy or wording alone does not establish either "
        "relationship.",
    ),
    "nigeria_math": (
        "Independently check Performance Objective judgments against the "
        "source-backed Theme, Sub-Theme, Topic, and PRIMARY ONE through PRIMARY "
        "THREE context. Reject reversed developmental direction, relationships "
        "inferred only from nearby source codes or hierarchy, and generic repetition "
        "that does not express extension or meaningful reinforcement.",
        "Judge only pairs of Performance Objective SFIs. Use the configured PRIMARY "
        "ONE through PRIMARY THREE sequence for developmental direction and use "
        "source-backed Theme, Sub-Theme, Topic, objective text, and Learning "
        "Components as evidence. Similar numbering, source proximity, or shared "
        "hierarchy may support consideration but never establishes a relationship by "
        "itself.",
    ),
    "pratham_science": (
        "Independently check each judgment within its same statement-type grain and "
        "the Class IX to Class X order. Preserve all trustworthy parent paths in this "
        "multi-parent framework, distinguish NCERT Learning Outcomes, Content Domain "
        "Specific Learning Outcomes, and Indicators, and reject cross-grain claims "
        "or claims established only by a shared Chapter, Content Domain, or Learning "
        "Component.",
        "Judge NCERT Learning Outcome pairs, Content Domain Specific Learning Outcome "
        "pairs, and Indicator pairs only within the same statement-type grain. Use "
        "the configured Class IX to Class X sequence for developmental direction and "
        "consider every trustworthy parent path in the framework's DAG. Shared "
        "Chapter, Content Domain, wording, or Learning Components can support a "
        "judgment but does not establish one by itself.",
    ),
    "rwanda_math": (
        "Independently check each Rwanda judgment within its same statement-type "
        "grain and the P1 through P3 order. Keep Grade Key Competence, Key Unit "
        "Competence, Knowledge Objective, Skills Objective, and Attitudes and Values "
        "Objective semantics distinct; reject cross-grain claims, reversed "
        "development, and claims based only on shared Unit, Topic Area, wording, or "
        "Learning Components.",
        "Judge Grade Key Competence, Key Unit Competence, Knowledge Objective, Skills "
        "Objective, and Attitudes and Values Objective pairs only within the same "
        "statement-type grain. Use the configured P1 through P3 sequence for "
        "developmental direction while preserving the distinct conceptual, "
        "procedural, and disposition meanings. Shared Unit, Topic Area, wording, or "
        "Learning Components may nominate but never establishes a relationship by "
        "itself.",
    ),
}
_PROFILE_STATEMENT_TYPES: dict[str, tuple[str, ...]] = {
    "ghana_english": ("Content Standard", "Indicator"),
    "ghana_math": ("Content Standard", "Indicator"),
    "madhi_math": ("Content",),
    "nigeria_math": ("Performance Objective",),
    "pratham_science": (
        "NCERT Learning Outcome",
        "Content Domain Specific Learning Outcome",
        "Indicator",
    ),
    "rwanda_math": (
        "Grade Key Competence",
        "Key Unit Competence",
        "Knowledge Objective",
        "Skills Objective",
        "Attitudes and Values Objective",
    ),
}
_VARIABLE_POLICY_FIELDS = (
    "builds_towards",
    "candidate_policy",
    "checker_instructions",
    "developmental_coordinate",
    "evidence_limits",
    "producer_instructions",
    "relates_to",
    "relationship_metadata",
    "request_batch_size",
    "retry",
    "unresolved_participation",
)


def _expected_lp_policy(profile_name: str) -> dict[str, Any]:
    """Build the complete expected LP policy for one reviewed curriculum profile.

    Parameters
    ----------
    profile_name
        Stable name of the curriculum profile under test.

    Returns
    -------
    dict[str, Any]
        Exact expected serialized LP policy.
    """

    checker_instructions, producer_instructions = _PROFILE_INSTRUCTIONS[profile_name]
    coordinate_statement_type, coordinate_values = _PROFILE_COORDINATES[profile_name]
    statement_types = _PROFILE_STATEMENT_TYPES[profile_name]

    return {
        "builds_towards": {
            "allowed_statement_type_pairs": [
                {
                    "source_statement_type": statement_type,
                    "target_statement_type": statement_type,
                }
                for statement_type in statement_types
            ]
        },
        "candidate_policy": deepcopy(_COMMON_CANDIDATE_POLICY),
        "checker_instructions": checker_instructions,
        "developmental_coordinate": {
            "ordered_values": list(coordinate_values),
            "statement_type": coordinate_statement_type,
        },
        "evidence_limits": deepcopy(_COMMON_EVIDENCE_LIMITS),
        "producer_instructions": producer_instructions,
        "relates_to": {
            "allowed_statement_type_pairs": [
                {
                    "first_statement_type": statement_type,
                    "second_statement_type": statement_type,
                }
                for statement_type in statement_types
            ]
        },
        "relationship_metadata": deepcopy(_COMMON_RELATIONSHIP_METADATA),
        "request_batch_size": 1,
        "retry": deepcopy(_COMMON_RETRY_POLICY),
        "unresolved_participation": "include_unresolved_with_warnings",
    }


def _load_profile_payload(profile_name: str = "ghana_math") -> dict[str, Any]:
    """Load a fresh runtime payload with a side-effect-free output location.

    Parameters
    ----------
    profile_name
        Stable name of the curriculum profile to load.

    Returns
    -------
    dict[str, Any]
        Parsed JSON runtime payload.
    """

    payload: dict[str, Any] = json.loads(
        _PROFILE_CONFIG_PATHS[profile_name].read_text(encoding="utf-8")
    )
    payload["page_ir_extraction"]["output_dir"] = str(PACKAGE_PATH / "backend/tests")
    payload["page_ir_extraction"]["pdf_fp"] = str(
        PACKAGE_PATH / "backend/tests/fixtures/utils/tanzania.pdf"
    )
    return payload


def _mapping_at_path(
    *, path: tuple[str | int, ...], payload: dict[str, Any]
) -> dict[str, Any]:
    """Return a mutable mapping at a nested runtime-config path.

    Parameters
    ----------
    path
        String keys and list indexes leading to the target mapping.
    payload
        Complete mutable runtime configuration.

    Returns
    -------
    dict[str, Any]
        Mutable mapping at the requested path.
    """

    current: Any = payload
    for part in path:
        current = current[part]

    assert isinstance(current, dict)
    return current


@PARAM(
    argnames=("profile_name",),
    argvalues=[(profile_name,) for profile_name in sorted(_PROFILE_CONFIG_PATHS)],
)
def test_all_six_profiles_match_complete_learning_progressions_policies(
    profile_name: str,
) -> None:
    """Every profile validates and exactly matches its complete reviewed LP policy.

    Parameters
    ----------
    profile_name
        Stable name of the curriculum profile under test.
    """

    parsed = RunConfig.model_validate(_load_profile_payload(profile_name))

    assert parsed.kgs is not None
    assert parsed.kgs.learning_progressions.model_dump() == _expected_lp_policy(
        profile_name
    )


def test_builds_towards_coordinate_type_may_supply_its_own_coordinate() -> None:
    """The coordinate statement type need not list itself in AS identity scope."""

    payload = _load_profile_payload()
    payload["kgs"]["lp"]["builds_towards"]["allowed_statement_type_pairs"] = [
        {"source_statement_type": "Grade", "target_statement_type": "Grade"}
    ]
    payload["kgs"]["lp"]["relates_to"]["allowed_statement_type_pairs"] = [
        {"first_statement_type": "Grade", "second_statement_type": "Grade"}
    ]

    parsed = RunConfig.model_validate(payload)

    assert parsed.kgs is not None
    pair = parsed.kgs.learning_progressions.builds_towards.allowed_statement_type_pairs[
        0
    ]
    assert pair.source_statement_type == "Grade"
    assert pair.target_statement_type == "Grade"


def test_builds_towards_type_without_coordinate_identity_scope_is_rejected() -> None:
    """A non-coordinate buildsTowards type must expose the coordinate in AS scope."""

    payload = _load_profile_payload()
    payload["kgs"]["as"]["identity_scope_statement_types"]["Indicator"] = ["Strand"]

    with pytest.raises(
        expected_exception=ValidationError,
        match="Every buildsTowards-participating statement type must expose",
    ):
        RunConfig.model_validate(payload)


def test_coordinate_order_is_preserved_for_complete_canonical_vocabulary() -> None:
    """Cross-validation preserves an explicitly configured canonical local order."""

    payload = _load_profile_payload()
    configured_order = ["BASIC 6", "BASIC 4", "BASIC 5"]
    payload["kgs"]["lp"]["developmental_coordinate"][
        "ordered_values"
    ] = configured_order

    parsed = RunConfig.model_validate(payload)

    assert parsed.kgs is not None
    assert (
        parsed.kgs.learning_progressions.developmental_coordinate.ordered_values
        == configured_order
    )


@PARAM(
    argnames=("coordinate_values",),
    argvalues=[
        (["BASIC 4", "BASIC 5"],),
        (["Basic 4", "BASIC 5", "BASIC 6"],),
        (["P1", "P2", "P3"],),
        (["BASIC 4", "BASIC 5", "BASIC 6", "BASIC 7"],),
    ],
)
def test_coordinate_policy_rejects_incomplete_noncanonical_or_copied_vocabulary(
    coordinate_values: list[str],
) -> None:
    """The LP coordinate vocabulary must equal the AS canonical value vocabulary.

    Parameters
    ----------
    coordinate_values
        Incomplete, alias-based, foreign, or extended coordinate vocabulary.
    """

    payload = _load_profile_payload()
    payload["kgs"]["lp"]["developmental_coordinate"][
        "ordered_values"
    ] = coordinate_values

    with pytest.raises(
        expected_exception=ValidationError,
        match="must contain exactly the canonical controlled_values",
    ):
        RunConfig.model_validate(payload)


def test_coordinate_statement_type_requires_local_grade_class_or_stage() -> None:
    """A known AS grouping cannot serve as the coordinate unless locally declared."""

    payload = _load_profile_payload()
    payload["kgs"]["lp"]["developmental_coordinate"]["statement_type"] = "Strand"

    with pytest.raises(
        expected_exception=ValidationError,
        match="must be declared by CreateKGConfig.as.grade_level_statement_types",
    ):
        RunConfig.model_validate(payload)


@PARAM(
    argnames=("donor_profile", "recipient_profile"),
    argvalues=list(permutations(sorted(_PROFILE_CONFIG_PATHS), 2)),
)
def test_cross_profile_learning_progressions_policy_copy_is_rejected(
    *, donor_profile: str, recipient_profile: str
) -> None:
    """No curriculum accepts another profile's complete LP policy unchanged.

    Parameters
    ----------
    donor_profile
        Curriculum whose LP section is copied.
    recipient_profile
        Different curriculum whose AS policy remains authoritative.
    """

    donor_payload = _load_profile_payload(donor_profile)
    recipient_payload = _load_profile_payload(recipient_profile)
    recipient_payload["kgs"]["lp"] = deepcopy(donor_payload["kgs"]["lp"])

    with pytest.raises(expected_exception=ValidationError):
        RunConfig.model_validate(recipient_payload)


def test_kgs_accepts_absent_namespace_only_when_entire_phase_is_skipped() -> None:
    """The LP namespace is required with kgs but kgs itself remains optional."""

    payload_without_kgs = _load_profile_payload()
    del payload_without_kgs["kgs"]
    assert RunConfig.model_validate(payload_without_kgs).kgs is None

    payload_without_lp = _load_profile_payload()
    del payload_without_lp["kgs"]["lp"]
    with pytest.raises(expected_exception=ValidationError) as exc_info:
        RunConfig.model_validate(payload_without_lp)

    assert any(
        error["loc"] == ("kgs", "lp") and error["type"] == "missing"
        for error in exc_info.value.errors()
    )


@PARAM(
    argnames=("path", "value"),
    argvalues=[
        (
            (
                "kgs",
                "lp",
                "builds_towards",
                "allowed_statement_type_pairs",
                0,
                "source_statement_type",
            ),
            "CONTENT STANDARD",
        ),
        (
            (
                "kgs",
                "lp",
                "builds_towards",
                "allowed_statement_type_pairs",
                0,
                "target_statement_type",
            ),
            "Unknown Standard",
        ),
        (
            ("kgs", "lp", "developmental_coordinate", "statement_type"),
            "grade",
        ),
        (
            (
                "kgs",
                "lp",
                "relates_to",
                "allowed_statement_type_pairs",
                0,
                "first_statement_type",
            ),
            "content_standard",
        ),
        (
            (
                "kgs",
                "lp",
                "relates_to",
                "allowed_statement_type_pairs",
                0,
                "second_statement_type",
            ),
            "Unknown Standard",
        ),
    ],
)
def test_learning_progressions_statement_types_must_be_canonical_and_known(
    *, path: tuple[str | int, ...], value: str
) -> None:
    """AS aliases and unknown labels are not canonical LP statement-type policy.

    Parameters
    ----------
    path
        Location of one LP statement-type reference.
    value
        AS alias or unknown statement-type label under test.
    """

    payload = _load_profile_payload()
    field_name = path[-1]
    assert isinstance(field_name, str)
    _mapping_at_path(path=path[:-1], payload=payload)[field_name] = value

    with pytest.raises(
        expected_exception=ValidationError,
        match="must use canonical statement_type labels",
    ):
        RunConfig.model_validate(payload)


@PARAM(
    argnames=("field_name",),
    argvalues=[(field_name,) for field_name in _VARIABLE_POLICY_FIELDS],
)
def test_lp_variable_policy_omissions_fail_in_complete_run_config(
    field_name: str,
) -> None:
    """Every curriculum-variable LP policy remains required after full wiring.

    Parameters
    ----------
    field_name
        Required LP field removed from an otherwise complete runtime config.
    """

    payload = _load_profile_payload()
    del payload["kgs"]["lp"][field_name]

    with pytest.raises(expected_exception=ValidationError) as exc_info:
        RunConfig.model_validate(payload)

    assert any(
        error["loc"] == ("kgs", "lp", field_name) and error["type"] == "missing"
        for error in exc_info.value.errors()
    )


def test_relates_to_only_type_without_coordinate_identity_scope_is_accepted() -> None:
    """Missing coordinate scope does not exclude an otherwise valid relatesTo type."""

    payload = _load_profile_payload()
    payload["kgs"]["as"]["identity_scope_statement_types"]["Indicator"] = ["Strand"]
    payload["kgs"]["lp"]["builds_towards"]["allowed_statement_type_pairs"] = [
        {
            "source_statement_type": "Content Standard",
            "target_statement_type": "Content Standard",
        }
    ]

    parsed = RunConfig.model_validate(payload)

    assert parsed.kgs is not None
    relates_to_types = {
        pair.first_statement_type
        for pair in parsed.kgs.learning_progressions.relates_to.allowed_statement_type_pairs
    }
    assert "Indicator" in relates_to_types


@PARAM(
    argnames=("field_name", "path", "value"),
    argvalues=[
        (
            "allow_same_rank_builds_towards",
            ("kgs", "lp", "developmental_coordinate"),
            False,
        ),
        ("algorithm_version", ("kgs", "lp", "candidate_policy"), "v1"),
        ("candidate_policy_version", ("kgs", "lp", "candidate_policy"), "v1"),
        (
            "canonical_source",
            ("kgs", "lp", "developmental_coordinate"),
            "identity_scope",
        ),
        ("checkpoint_policy", ("kgs", "lp"), "validated_prefix"),
        (
            "coordinate_source",
            ("kgs", "lp", "developmental_coordinate"),
            "identity_scope",
        ),
        ("direction", ("kgs", "lp", "developmental_coordinate"), "lower_to_higher"),
        ("enabled_signals", ("kgs", "lp", "candidate_policy"), ["hierarchy"]),
        ("fingerprint_inputs", ("kgs", "lp", "candidate_policy"), ["config"]),
        ("fingerprint_mismatch_policy", ("kgs", "lp"), "reject"),
        ("forced_relationships", ("kgs", "lp"), []),
        ("license_source", ("kgs", "lp", "relationship_metadata"), "framework"),
        ("max_failed_pair_count", ("kgs", "lp"), 1),
        ("max_forward_rank_gap", ("kgs", "lp", "developmental_coordinate"), None),
        ("maximum_failed_pairs", ("kgs", "lp", "retry"), 1),
        (
            "missing_coordinate_policy",
            ("kgs", "lp", "developmental_coordinate"),
            "relates_to_only",
        ),
        ("ranking", ("kgs", "lp", "candidate_policy"), ["score"]),
        ("rank_gap_policy", ("kgs", "lp", "developmental_coordinate"), "unlimited"),
        (
            "required_provenance",
            ("kgs", "lp", "relationship_metadata"),
            ["candidate_id"],
        ),
        ("resume_policy", ("kgs", "lp"), "earliest_unfinished"),
        ("semantic_overrides", ("kgs", "lp"), []),
        ("strategies", ("kgs", "lp", "candidate_policy"), ["hierarchy"]),
        ("technology", ("kgs", "lp", "candidate_policy"), "non_embedding"),
        ("tie_breaking", ("kgs", "lp", "candidate_policy"), ["candidate_id"]),
    ],
)
def test_runtime_configuration_rejects_code_owned_invariant_overrides(
    *, field_name: str, path: tuple[str | int, ...], value: object
) -> None:
    """Full runtime loading rejects fields that attempt to override invariants.

    Parameters
    ----------
    field_name
        Unapproved runtime field under test.
    path
        Location where the field attempts to override code-owned behavior.
    value
        Representative override value.
    """

    payload = _load_profile_payload()
    _mapping_at_path(path=path, payload=payload)[field_name] = value

    with pytest.raises(expected_exception=ValidationError) as exc_info:
        RunConfig.model_validate(payload)

    assert any(
        error["loc"] == (*path, field_name) and error["type"] == "extra_forbidden"
        for error in exc_info.value.errors()
    )
