"""Test the intrinsic Learning Progressions configuration schema contract."""

# Standard Library
from copy import deepcopy
from typing import Any

# Third Party Library
import pytest

from pydantic import BaseModel, ValidationError

# Package Library
from kgfeg.schemas import (
    _CreateKGLearningProgressionsBuildsTowardsPolicy,
    _CreateKGLearningProgressionsBuildsTowardsStatementTypePair,
    _CreateKGLearningProgressionsCandidateBudgetConfig,
    _CreateKGLearningProgressionsCandidatePolicy,
    _CreateKGLearningProgressionsConfig,
    _CreateKGLearningProgressionsDevelopmentalCoordinatePolicy,
    _CreateKGLearningProgressionsEvidenceLimits,
    _CreateKGLearningProgressionsRelatesToPolicy,
    _CreateKGLearningProgressionsRelatesToStatementTypePair,
    _CreateKGLearningProgressionsRelationshipMetadataPolicy,
    _CreateKGLearningProgressionsRetryPolicy,
)
from tests.constants import PARAM

_APPROVED_ATTRIBUTION_TEMPLATE = (
    "Learning progression relationship generated by IDinsight using an LLM "
    "producer/checker workflow. Source framework attribution: "
    "{source_attribution_statement}. This inferred relationship was not stated or "
    "endorsed by the source publisher."
)
_MISSING = object()


def _assert_extra_field_rejected(
    *, field_name: str, path: tuple[str | int, ...], value: object
) -> None:
    """Assert that an extra LP configuration field fails at its actual location.

    Parameters
    ----------
    field_name
        Name of the unapproved runtime field.
    path
        Location of the model whose strict field boundary is under test.
    value
        Representative value for the unapproved field.
    """

    payload = _valid_lp_config()
    _nested_mapping(path=path, payload=payload)[field_name] = value

    with pytest.raises(expected_exception=ValidationError) as exc_info:
        _CreateKGLearningProgressionsConfig.model_validate(payload)

    assert any(
        error["loc"] == (*path, field_name) and error["type"] == "extra_forbidden"
        for error in exc_info.value.errors()
    )


def _nested_mapping(
    *, path: tuple[str | int, ...], payload: dict[str, Any]
) -> dict[str, Any]:
    """Return the nested mapping at one path in an LP configuration payload.

    Parameters
    ----------
    path
        String keys and list indexes leading to the target mapping.
    payload
        Complete mutable LP configuration payload.

    Returns
    -------
    dict[str, Any]
        Mutable mapping at the requested path.
    """

    current: Any = payload
    for part in path:
        current = current[part]

    assert isinstance(current, dict)
    return current


def _valid_lp_config() -> dict[str, Any]:
    """Build one complete, intrinsically valid LP configuration payload.

    Returns
    -------
    dict[str, Any]
        A fresh payload containing every required top-level and nested field.
    """

    return {
        "builds_towards": {
            "allowed_statement_type_pairs": [
                {
                    "source_statement_type": "Content",
                    "target_statement_type": "Content",
                }
            ]
        },
        "candidate_policy": {
            "budgets": {
                "max_candidates_per_sfi": 5,
                "max_total_candidates": 50,
            }
        },
        "checker_instructions": "Reject claims not supported by the request.",
        "developmental_coordinate": {
            "ordered_values": ["Class-1", "Class-2"],
            "statement_type": "Class",
        },
        "evidence_limits": {
            "max_ancestor_path_depth": 3,
            "max_ancestor_paths_per_sfi": 2,
            "max_learning_components_per_sfi": 4,
            "max_source_evidence_characters_per_sfi": 500,
            "max_source_evidence_items_per_sfi": 3,
        },
        "producer_instructions": "Judge only the permitted relationship outcomes.",
        "relates_to": {
            "allowed_statement_type_pairs": [
                {
                    "first_statement_type": "Content",
                    "second_statement_type": "Content",
                }
            ]
        },
        "relationship_metadata": {
            "approved_by": "IDinsight",
            "attribution_statement_template": _APPROVED_ATTRIBUTION_TEMPLATE,
            "author": "LLM generated",
            "provider": "IDinsight",
        },
        "request_batch_size": 1,
        "retry": {"checker_max_retries": 0, "producer_max_retries": 0},
        "unresolved_participation": "include_unresolved_with_warnings",
    }


_MODEL_CASES: list[tuple[type[BaseModel], set[str], dict[str, Any]]] = [
    (
        _CreateKGLearningProgressionsBuildsTowardsPolicy,
        {"allowed_statement_type_pairs"},
        _valid_lp_config()["builds_towards"],
    ),
    (
        _CreateKGLearningProgressionsBuildsTowardsStatementTypePair,
        {"source_statement_type", "target_statement_type"},
        _valid_lp_config()["builds_towards"]["allowed_statement_type_pairs"][0],
    ),
    (
        _CreateKGLearningProgressionsCandidateBudgetConfig,
        {"max_candidates_per_sfi", "max_total_candidates"},
        _valid_lp_config()["candidate_policy"]["budgets"],
    ),
    (
        _CreateKGLearningProgressionsCandidatePolicy,
        {"budgets"},
        _valid_lp_config()["candidate_policy"],
    ),
    (
        _CreateKGLearningProgressionsConfig,
        {
            "builds_towards",
            "candidate_policy",
            "checker_instructions",
            "developmental_coordinate",
            "evidence_limits",
            "producer_instructions",
            "relates_to",
            "relationship_metadata",
            "request_batch_size",
            "retry",
            "unresolved_participation",
        },
        _valid_lp_config(),
    ),
    (
        _CreateKGLearningProgressionsDevelopmentalCoordinatePolicy,
        {"ordered_values", "statement_type"},
        _valid_lp_config()["developmental_coordinate"],
    ),
    (
        _CreateKGLearningProgressionsEvidenceLimits,
        {
            "max_ancestor_path_depth",
            "max_ancestor_paths_per_sfi",
            "max_learning_components_per_sfi",
            "max_source_evidence_characters_per_sfi",
            "max_source_evidence_items_per_sfi",
        },
        _valid_lp_config()["evidence_limits"],
    ),
    (
        _CreateKGLearningProgressionsRelatesToPolicy,
        {"allowed_statement_type_pairs"},
        _valid_lp_config()["relates_to"],
    ),
    (
        _CreateKGLearningProgressionsRelatesToStatementTypePair,
        {"first_statement_type", "second_statement_type"},
        _valid_lp_config()["relates_to"]["allowed_statement_type_pairs"][0],
    ),
    (
        _CreateKGLearningProgressionsRelationshipMetadataPolicy,
        {
            "approved_by",
            "attribution_statement_template",
            "author",
            "provider",
        },
        _valid_lp_config()["relationship_metadata"],
    ),
    (
        _CreateKGLearningProgressionsRetryPolicy,
        {"checker_max_retries", "producer_max_retries"},
        _valid_lp_config()["retry"],
    ),
]

_INTEGER_CONTROLS: list[tuple[tuple[str, ...], bool]] = [
    (("candidate_policy", "budgets", "max_candidates_per_sfi"), True),
    (("candidate_policy", "budgets", "max_total_candidates"), True),
    (("evidence_limits", "max_ancestor_path_depth"), True),
    (("evidence_limits", "max_ancestor_paths_per_sfi"), True),
    (("evidence_limits", "max_learning_components_per_sfi"), True),
    (
        ("evidence_limits", "max_source_evidence_characters_per_sfi"),
        True,
    ),
    (("evidence_limits", "max_source_evidence_items_per_sfi"), True),
    (("request_batch_size",), True),
    (("retry", "checker_max_retries"), False),
    (("retry", "producer_max_retries"), False),
]

_INVALID_INTEGER_CASES: list[tuple[object, tuple[str, ...]]] = []
for _path, _positive_only in _INTEGER_CONTROLS:
    for _invalid_value in (False, True, "1", 1.0):
        _INVALID_INTEGER_CASES.append((_invalid_value, _path))
    _INVALID_INTEGER_CASES.append((-1, _path))
    if _positive_only:
        _INVALID_INTEGER_CASES.append((0, _path))


@PARAM(
    argnames=("unresolved_participation",),
    argvalues=[("exclude_unresolved",), ("include_unresolved_with_warnings",)],
)
def test_lp_config_accepts_both_unresolved_participation_states(
    unresolved_participation: str,
) -> None:
    """Both complete profile-wide unresolved-participation states are valid.

    Parameters
    ----------
    unresolved_participation
        One of the two approved profile-wide unresolved-participation states.
    """

    payload = _valid_lp_config()
    payload["unresolved_participation"] = unresolved_participation

    parsed = _CreateKGLearningProgressionsConfig.model_validate(payload)

    assert parsed.unresolved_participation == unresolved_participation


def test_lp_config_accepts_complete_valid_nested_shape() -> None:
    """A complete approved LP configuration round-trips through every nested model."""

    payload = _valid_lp_config()

    parsed = _CreateKGLearningProgressionsConfig.model_validate(payload)

    assert parsed.model_dump() == payload


def test_lp_config_accepts_integer_boundaries() -> None:
    """Positive controls accept one and retry controls accept zero."""

    payload = _valid_lp_config()
    for path, positive_only in _INTEGER_CONTROLS:
        parent = _nested_mapping(path=path[:-1], payload=payload)
        parent[path[-1]] = 1 if positive_only else 0

    parsed = _CreateKGLearningProgressionsConfig.model_validate(payload)

    assert parsed.request_batch_size == 1
    assert parsed.retry.checker_max_retries == 0
    assert parsed.retry.producer_max_retries == 0


@PARAM(
    argnames=("expected_fields", "model_type"),
    argvalues=[
        (expected_fields, model_type) for model_type, expected_fields, _ in _MODEL_CASES
    ],
)
def test_lp_config_defines_exact_required_field_inventories(
    *, expected_fields: set[str], model_type: type[BaseModel]
) -> None:
    """Each intrinsic LP model exposes exactly its approved required fields.

    Parameters
    ----------
    expected_fields
        Complete field inventory independently derived for the model.
    model_type
        Intrinsic LP model under inspection.
    """

    assert set(model_type.model_fields) == expected_fields
    assert all(field.is_required() for field in model_type.model_fields.values())


def test_lp_config_preserves_distinct_reverse_directional_pairs() -> None:
    """Reverse directional type permissions remain distinct and valid."""

    payload = _valid_lp_config()
    payload["builds_towards"]["allowed_statement_type_pairs"] = [
        {
            "source_statement_type": "Content",
            "target_statement_type": "Indicator",
        },
        {
            "source_statement_type": "Indicator",
            "target_statement_type": "Content",
        },
    ]

    parsed = _CreateKGLearningProgressionsConfig.model_validate(payload)

    assert len(parsed.builds_towards.allowed_statement_type_pairs) == 2


@PARAM(
    argnames=("model_type", "required_field", "valid_payload"),
    argvalues=[
        (model_type, required_field, valid_payload)
        for model_type, expected_fields, valid_payload in _MODEL_CASES
        for required_field in sorted(expected_fields)
    ],
)
def test_lp_config_rejects_all_required_field_omissions(
    *,
    model_type: type[BaseModel],
    required_field: str,
    valid_payload: dict[str, Any],
) -> None:
    """Omitting any top-level or nested intrinsic LP field fails validation.

    Parameters
    ----------
    model_type
        Intrinsic LP model under test.
    required_field
        Required field removed from its otherwise valid payload.
    valid_payload
        Complete valid payload for the selected model.
    """

    payload = deepcopy(valid_payload)
    del payload[required_field]

    with pytest.raises(expected_exception=ValidationError) as exc_info:
        model_type.model_validate(payload)

    assert any(
        error["loc"] == (required_field,) and error["type"] == "missing"
        for error in exc_info.value.errors()
    )


@PARAM(
    argnames=("path",),
    argvalues=[
        (("checker_instructions",),),
        (("producer_instructions",),),
        (("developmental_coordinate", "statement_type"),),
        (
            (
                "builds_towards",
                "allowed_statement_type_pairs",
                0,
                "source_statement_type",
            ),
        ),
        (
            (
                "builds_towards",
                "allowed_statement_type_pairs",
                0,
                "target_statement_type",
            ),
        ),
        (
            (
                "relates_to",
                "allowed_statement_type_pairs",
                0,
                "first_statement_type",
            ),
        ),
        (
            (
                "relates_to",
                "allowed_statement_type_pairs",
                0,
                "second_statement_type",
            ),
        ),
    ],
)
def test_lp_config_rejects_blank_required_strings(path: tuple[str | int, ...]) -> None:
    """Intrinsic policy strings reject whitespace-only values.

    Parameters
    ----------
    path
        Location of one required non-empty string field.
    """

    payload = _valid_lp_config()
    field_name = path[-1]
    assert isinstance(field_name, str)
    _nested_mapping(path=path[:-1], payload=payload)[field_name] = "   "

    with pytest.raises(expected_exception=ValidationError):
        _CreateKGLearningProgressionsConfig.model_validate(payload)


@PARAM(
    argnames=("field_name", "value"),
    argvalues=[
        ("algorithm", "deterministic_non_embedding"),
        ("algorithm_version", "1"),
        ("candidate_policy_version", "v1"),
        ("enabled_signals", ["hierarchy", "text"]),
        ("fingerprint_inputs", ["config", "upstream_bundle"]),
        ("implementation_identifier", "builtin-v1"),
        ("parameters", {"minimum_similarity": 0.5}),
        ("ranking", ["score_descending"]),
        ("ranking_inputs", ["text_similarity"]),
        ("strategies", ["hierarchy", "shared_lc"]),
        ("technology", "lexical"),
        ("tie_breaking", ["candidate_id"]),
    ],
)
def test_lp_config_rejects_candidate_policy_override_fields(
    *, field_name: str, value: object
) -> None:
    """Candidate policy rejects algorithm, signal, ranking, and version selectors.

    Parameters
    ----------
    field_name
        Candidate-policy field owned universally by code.
    value
        Representative runtime override value.
    """

    _assert_extra_field_rejected(
        field_name=field_name, path=("candidate_policy",), value=value
    )


@PARAM(
    argnames=("field_name", "value"),
    argvalues=[
        ("allow_same_rank_builds_towards", False),
        ("canonical_source", "identity_scope"),
        ("coordinate_source", "identity_scope"),
        ("direction", "lower_to_higher"),
        ("max_forward_rank_gap", None),
        ("missing_coordinate_policy", "relates_to_only"),
        ("rank_gap_policy", "unlimited"),
    ],
)
def test_lp_config_rejects_coordinate_override_fields(
    *, field_name: str, value: object
) -> None:
    """Coordinate configuration rejects code-owned resolution and rank selectors.

    Parameters
    ----------
    field_name
        Coordinate behavior field owned universally by code.
    value
        Representative runtime override value.
    """

    _assert_extra_field_rejected(
        field_name=field_name, path=("developmental_coordinate",), value=value
    )


@PARAM(
    argnames=("coordinate_values",),
    argvalues=[
        ([],),
        ([""],),
        (["   "],),
        (["Class-1", "class 1"],),
        (["P1", "Ｐ１"],),
    ],
)
def test_lp_config_rejects_coordinate_values_that_are_empty_or_normalized_duplicates(
    coordinate_values: list[str],
) -> None:
    """The coordinate order is non-empty and unique after canonical normalization.

    Parameters
    ----------
    coordinate_values
        Empty, blank, or normalization-colliding ordered coordinate values.
    """

    payload = _valid_lp_config()
    payload["developmental_coordinate"]["ordered_values"] = coordinate_values

    with pytest.raises(expected_exception=ValidationError):
        _CreateKGLearningProgressionsConfig.model_validate(payload)


@PARAM(
    argnames=("field_name", "path", "value"),
    argvalues=[
        ("batch_size", (), 1),
        ("buildsTowards", (), {}),
        ("candidate_budgets", ("candidate_policy",), {}),
        ("checker_prompt", (), "Check the relationship."),
        ("developmental_dimension", (), {}),
        ("max_candidates_per_sfi", ("candidate_policy",), 5),
        ("metadata", (), {}),
        ("producer_prompt", (), "Judge the relationship."),
        ("relatesTo", (), {}),
        ("retry_policy", (), {}),
        ("unresolved_policy", (), "exclude_unresolved"),
    ],
)
def test_lp_config_rejects_deprecated_or_compatibility_fields(
    *, field_name: str, path: tuple[str | int, ...], value: object
) -> None:
    """Deprecated spellings and flattened compatibility inputs remain unsupported.

    Parameters
    ----------
    field_name
        Deprecated or compatibility field name.
    path
        Location where a compatibility layer might plausibly accept the field.
    value
        Representative legacy value.
    """

    _assert_extra_field_rejected(field_name=field_name, path=path, value=value)


def test_lp_config_rejects_duplicate_directional_pairs() -> None:
    """The same directional statement-type permission cannot appear twice."""

    payload = _valid_lp_config()
    pair = payload["builds_towards"]["allowed_statement_type_pairs"][0]
    payload["builds_towards"]["allowed_statement_type_pairs"].append(deepcopy(pair))

    with pytest.raises(
        expected_exception=ValidationError, match="duplicate directional pair"
    ):
        _CreateKGLearningProgressionsConfig.model_validate(payload)


@PARAM(argnames=("relation_policy",), argvalues=[("builds_towards",), ("relates_to",)])
def test_lp_config_rejects_empty_pair_matrices(relation_policy: str) -> None:
    """Both closed-world relation policies require at least one type pair.

    Parameters
    ----------
    relation_policy
        Relationship policy whose complete pair matrix is emptied.
    """

    payload = _valid_lp_config()
    payload[relation_policy]["allowed_statement_type_pairs"] = []

    with pytest.raises(expected_exception=ValidationError):
        _CreateKGLearningProgressionsConfig.model_validate(payload)


@PARAM(
    argnames=("field_name", "path", "value"),
    argvalues=[
        ("failure_tolerance", (), {"maximum_failed_pairs": 1}),
        ("max_failed_pair_count", (), 1),
        ("max_failed_pair_rate", (), 0.01),
        ("maximum_failed_pairs", ("retry",), 1),
        ("per_profile_failure_threshold", (), 1),
    ],
)
def test_lp_config_rejects_failure_tolerance_fields(
    *, field_name: str, path: tuple[str | int, ...], value: object
) -> None:
    """Retry configuration cannot weaken zero-tolerance processing failure policy.

    Parameters
    ----------
    field_name
        Unapproved failed-pair tolerance field.
    path
        Plausible top-level or retry-policy location.
    value
        Representative tolerance value.
    """

    _assert_extra_field_rejected(field_name=field_name, path=path, value=value)


@PARAM(argnames=("invalid_value", "path"), argvalues=_INVALID_INTEGER_CASES)
def test_lp_config_rejects_invalid_integer_controls(
    *, invalid_value: object, path: tuple[str, ...]
) -> None:
    """Every LP integer control rejects coercion and its invalid lower boundary.

    Parameters
    ----------
    invalid_value
        Boolean, numeric string, integral float, zero, or negative value that the
        selected control must reject.
    path
        Location of one candidate, evidence, batching, or retry integer control.
    """

    payload = _valid_lp_config()
    _nested_mapping(path=path[:-1], payload=payload)[path[-1]] = invalid_value

    with pytest.raises(expected_exception=ValidationError):
        _CreateKGLearningProgressionsConfig.model_validate(payload)


@PARAM(
    argnames=("field_name", "invalid_value"),
    argvalues=[
        ("approved_by", "Curriculum publisher"),
        ("approved_by", "idinsight"),
        (
            "attribution_statement_template",
            _APPROVED_ATTRIBUTION_TEMPLATE.replace("IDinsight", "Publisher", 1),
        ),
        (
            "attribution_statement_template",
            _APPROVED_ATTRIBUTION_TEMPLATE.replace(
                "{source_attribution_statement}", "{source_attribution}"
            ),
        ),
        (
            "attribution_statement_template",
            _APPROVED_ATTRIBUTION_TEMPLATE.replace(
                "{source_attribution_statement}", "source attribution"
            ),
        ),
        ("attribution_statement_template", f"{_APPROVED_ATTRIBUTION_TEMPLATE} Extra"),
        ("author", "IDinsight"),
        ("author", "LLM Generated"),
        ("provider", "Curriculum publisher"),
        ("provider", "idinsight"),
    ],
)
def test_lp_config_rejects_invalid_relationship_metadata(
    *, field_name: str, invalid_value: str
) -> None:
    """Relationship metadata accepts only the exact approved ownership disclosure.

    Parameters
    ----------
    field_name
        Relationship metadata field being falsified.
    invalid_value
        Non-approved literal or attribution template.
    """

    payload = _valid_lp_config()
    payload["relationship_metadata"][field_name] = invalid_value

    with pytest.raises(expected_exception=ValidationError):
        _CreateKGLearningProgressionsConfig.model_validate(payload)


@PARAM(
    argnames=("field_name", "path", "value"),
    argvalues=[
        ("license_source", ("relationship_metadata",), "framework"),
        ("provenance_fields", ("relationship_metadata",), ["candidate_id"]),
        ("required_provenance", (), ["candidate_id"]),
        ("retain_source_provenance", ("relationship_metadata",), True),
        ("retained_provenance", ("relationship_metadata",), ["candidate_id"]),
    ],
)
def test_lp_config_rejects_license_and_provenance_selectors(
    *, field_name: str, path: tuple[str | int, ...], value: object
) -> None:
    """Metadata cannot select source-license inheritance or provenance categories.

    Parameters
    ----------
    field_name
        License or provenance selector owned universally by code.
    path
        Plausible top-level or metadata-policy location.
    value
        Representative runtime selector value.
    """

    _assert_extra_field_rejected(field_name=field_name, path=path, value=value)


@PARAM(
    argnames=("invalid_state",),
    argvalues=[(_MISSING,), (None,), ("",), ("include_some",)],
)
def test_lp_config_rejects_missing_or_unknown_unresolved_participation(
    invalid_state: object,
) -> None:
    """The unresolved-participation policy has no default or third state.

    Parameters
    ----------
    invalid_state
        Missing sentinel or an unapproved policy state.
    """

    payload = _valid_lp_config()
    if invalid_state is _MISSING:
        del payload["unresolved_participation"]
    else:
        payload["unresolved_participation"] = invalid_state

    with pytest.raises(expected_exception=ValidationError):
        _CreateKGLearningProgressionsConfig.model_validate(payload)


@PARAM(
    argnames=("field_name", "value"),
    argvalues=[
        ("checkpoint_policy", "validated_prefix"),
        ("fingerprint_mismatch_policy", "fail"),
        ("resume_mode", "earliest_unfinished"),
        ("resume_policy", "earliest_unfinished"),
        ("reuse_prefix", True),
        ("stale_input_policy", "reject"),
    ],
)
def test_lp_config_rejects_resume_and_checkpoint_policy_fields(
    *, field_name: str, value: object
) -> None:
    """Configuration cannot select checkpoint, resume, or stale-input behavior.

    Parameters
    ----------
    field_name
        Checkpoint, resume, or stale-input field owned universally by code.
    value
        Representative runtime policy value.
    """

    _assert_extra_field_rejected(field_name=field_name, path=(), value=value)


@PARAM(argnames=("reverse_pair",), argvalues=[(False,), (True,)])
def test_lp_config_rejects_reverse_and_duplicate_unordered_pairs(
    reverse_pair: bool,
) -> None:
    """An unordered type pair cannot recur in the same or reverse field order.

    Parameters
    ----------
    reverse_pair
        Whether the duplicate swaps the two semantically unordered endpoints.
    """

    payload = _valid_lp_config()
    pairs = payload["relates_to"]["allowed_statement_type_pairs"]
    pairs[0] = {
        "first_statement_type": "Content Standard",
        "second_statement_type": "Indicator",
    }
    duplicate = deepcopy(pairs[0])
    if reverse_pair:
        duplicate = {
            "first_statement_type": "Indicator",
            "second_statement_type": "Content Standard",
        }
    pairs.append(duplicate)

    with pytest.raises(
        expected_exception=ValidationError,
        match="duplicate or reverse-duplicate unordered pairs",
    ):
        _CreateKGLearningProgressionsConfig.model_validate(payload)


@PARAM(
    argnames=("path",),
    argvalues=[
        ((),),
        (("builds_towards",),),
        (("builds_towards", "allowed_statement_type_pairs", 0),),
        (("candidate_policy",),),
        (("candidate_policy", "budgets"),),
        (("developmental_coordinate",),),
        (("evidence_limits",),),
        (("relates_to",),),
        (("relates_to", "allowed_statement_type_pairs", 0),),
        (("relationship_metadata",),),
        (("retry",),),
    ],
)
def test_lp_config_rejects_unknown_fields_at_every_nested_level(
    path: tuple[str | int, ...],
) -> None:
    """Strict extra-field behavior applies to the complete nested LP schema.

    Parameters
    ----------
    path
        Location of one intrinsic LP model boundary.
    """

    _assert_extra_field_rejected(
        field_name="unexpected_runtime_policy", path=path, value=True
    )


@PARAM(
    argnames=("field_name", "value"),
    argvalues=[
        ("unresolved_exceptions", ["case-identifier-uuid"]),
        ("unresolved_participation_overrides", {}),
        ("unresolved_sidecar", "unresolved-exceptions.json"),
    ],
)
def test_lp_config_rejects_unresolved_participation_exception_fields(
    *, field_name: str, value: object
) -> None:
    """Unresolved participation has no per-SFI selector or exception sidecar.

    Parameters
    ----------
    field_name
        Unapproved per-SFI exception or sidecar field.
    value
        Representative exception selector value.
    """

    _assert_extra_field_rejected(field_name=field_name, path=(), value=value)
